<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.AuthTimeOut</code>
 */
class AuthTimeOut extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Action = 1;</code>
     */
    protected $Action = '';
    /**
     * Generated from protobuf field <code>double Time = 2;</code>
     */
    protected $Time = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Action
     *     @type float $Time
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Action = 1;</code>
     * @return string
     */
    public function getAction()
    {
        return $this->Action;
    }

    /**
     * Generated from protobuf field <code>string Action = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkString($var, True);
        $this->Action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double Time = 2;</code>
     * @return float
     */
    public function getTime()
    {
        return $this->Time;
    }

    /**
     * Generated from protobuf field <code>double Time = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkDouble($var);
        $this->Time = $var;

        return $this;
    }

}

