<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.AuthResponseConfig</code>
 */
class AuthResponseConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.AuthCacheAction CacheAction = 1;</code>
     */
    protected $CacheAction = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.StatusCodeAction StatusCodeAction = 2;</code>
     */
    protected $StatusCodeAction = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.ResponseAction ResponseAction = 3;</code>
     */
    protected $ResponseAction = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.AuthTimeOut TimeOutAction = 4;</code>
     */
    protected $TimeOutAction = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\AuthCacheAction $CacheAction
     *     @type \Byteplus\Service\Vod\Models\Business\StatusCodeAction $StatusCodeAction
     *     @type \Byteplus\Service\Vod\Models\Business\ResponseAction $ResponseAction
     *     @type \Byteplus\Service\Vod\Models\Business\AuthTimeOut $TimeOutAction
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.AuthCacheAction CacheAction = 1;</code>
     * @return \Byteplus\Service\Vod\Models\Business\AuthCacheAction|null
     */
    public function getCacheAction()
    {
        return $this->CacheAction;
    }

    public function hasCacheAction()
    {
        return isset($this->CacheAction);
    }

    public function clearCacheAction()
    {
        unset($this->CacheAction);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.AuthCacheAction CacheAction = 1;</code>
     * @param \Byteplus\Service\Vod\Models\Business\AuthCacheAction $var
     * @return $this
     */
    public function setCacheAction($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\AuthCacheAction::class);
        $this->CacheAction = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.StatusCodeAction StatusCodeAction = 2;</code>
     * @return \Byteplus\Service\Vod\Models\Business\StatusCodeAction|null
     */
    public function getStatusCodeAction()
    {
        return $this->StatusCodeAction;
    }

    public function hasStatusCodeAction()
    {
        return isset($this->StatusCodeAction);
    }

    public function clearStatusCodeAction()
    {
        unset($this->StatusCodeAction);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.StatusCodeAction StatusCodeAction = 2;</code>
     * @param \Byteplus\Service\Vod\Models\Business\StatusCodeAction $var
     * @return $this
     */
    public function setStatusCodeAction($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\StatusCodeAction::class);
        $this->StatusCodeAction = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.ResponseAction ResponseAction = 3;</code>
     * @return \Byteplus\Service\Vod\Models\Business\ResponseAction|null
     */
    public function getResponseAction()
    {
        return $this->ResponseAction;
    }

    public function hasResponseAction()
    {
        return isset($this->ResponseAction);
    }

    public function clearResponseAction()
    {
        unset($this->ResponseAction);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.ResponseAction ResponseAction = 3;</code>
     * @param \Byteplus\Service\Vod\Models\Business\ResponseAction $var
     * @return $this
     */
    public function setResponseAction($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\ResponseAction::class);
        $this->ResponseAction = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.AuthTimeOut TimeOutAction = 4;</code>
     * @return \Byteplus\Service\Vod\Models\Business\AuthTimeOut|null
     */
    public function getTimeOutAction()
    {
        return $this->TimeOutAction;
    }

    public function hasTimeOutAction()
    {
        return isset($this->TimeOutAction);
    }

    public function clearTimeOutAction()
    {
        unset($this->TimeOutAction);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.AuthTimeOut TimeOutAction = 4;</code>
     * @param \Byteplus\Service\Vod\Models\Business\AuthTimeOut $var
     * @return $this
     */
    public function setTimeOutAction($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\AuthTimeOut::class);
        $this->TimeOutAction = $var;

        return $this;
    }

}

