<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.AuthRequestHeaderRule</code>
 */
class AuthRequestHeaderRule extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.RequestHeaderComponent RequestHeaderComponents = 1;</code>
     */
    protected $RequestHeaderComponents = null;
    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.RequestHeaderInstance RequestHeaderInstances = 2;</code>
     */
    private $RequestHeaderInstances;
    /**
     * Generated from protobuf field <code>string RequestHost = 3;</code>
     */
    protected $RequestHost = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\RequestHeaderComponent $RequestHeaderComponents
     *     @type \Byteplus\Service\Vod\Models\Business\RequestHeaderInstance[]|\Google\Protobuf\Internal\RepeatedField $RequestHeaderInstances
     *     @type string $RequestHost
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.RequestHeaderComponent RequestHeaderComponents = 1;</code>
     * @return \Byteplus\Service\Vod\Models\Business\RequestHeaderComponent|null
     */
    public function getRequestHeaderComponents()
    {
        return $this->RequestHeaderComponents;
    }

    public function hasRequestHeaderComponents()
    {
        return isset($this->RequestHeaderComponents);
    }

    public function clearRequestHeaderComponents()
    {
        unset($this->RequestHeaderComponents);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.RequestHeaderComponent RequestHeaderComponents = 1;</code>
     * @param \Byteplus\Service\Vod\Models\Business\RequestHeaderComponent $var
     * @return $this
     */
    public function setRequestHeaderComponents($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\RequestHeaderComponent::class);
        $this->RequestHeaderComponents = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.RequestHeaderInstance RequestHeaderInstances = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRequestHeaderInstances()
    {
        return $this->RequestHeaderInstances;
    }

    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.RequestHeaderInstance RequestHeaderInstances = 2;</code>
     * @param \Byteplus\Service\Vod\Models\Business\RequestHeaderInstance[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRequestHeaderInstances($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Byteplus\Service\Vod\Models\Business\RequestHeaderInstance::class);
        $this->RequestHeaderInstances = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string RequestHost = 3;</code>
     * @return string
     */
    public function getRequestHost()
    {
        return $this->RequestHost;
    }

    /**
     * Generated from protobuf field <code>string RequestHost = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->RequestHost = $var;

        return $this;
    }

}

