<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.BriefDomainInfo</code>
 */
class BriefDomainInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *域名
     *
     * Generated from protobuf field <code>string Domain = 1;</code>
     */
    protected $Domain = '';
    /**
     *空间名
     *
     * Generated from protobuf field <code>string SpaceName = 2;</code>
     */
    protected $SpaceName = '';
    /**
     *域名类型，play-播放域名，image-封面域名
     *
     * Generated from protobuf field <code>string DomainType = 3;</code>
     */
    protected $DomainType = '';
    /**
     *源站类型
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.SourceStationType SourceStationType = 4;</code>
     */
    protected $SourceStationType = 0;
    /**
     *签算类型
     *
     * Generated from protobuf field <code>string AuthType = 5;</code>
     */
    protected $AuthType = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Domain
     *          域名
     *     @type string $SpaceName
     *          空间名
     *     @type string $DomainType
     *          域名类型，play-播放域名，image-封面域名
     *     @type int $SourceStationType
     *          源站类型
     *     @type string $AuthType
     *          签算类型
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     *域名
     *
     * Generated from protobuf field <code>string Domain = 1;</code>
     * @return string
     */
    public function getDomain()
    {
        return $this->Domain;
    }

    /**
     *域名
     *
     * Generated from protobuf field <code>string Domain = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDomain($var)
    {
        GPBUtil::checkString($var, True);
        $this->Domain = $var;

        return $this;
    }

    /**
     *空间名
     *
     * Generated from protobuf field <code>string SpaceName = 2;</code>
     * @return string
     */
    public function getSpaceName()
    {
        return $this->SpaceName;
    }

    /**
     *空间名
     *
     * Generated from protobuf field <code>string SpaceName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSpaceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->SpaceName = $var;

        return $this;
    }

    /**
     *域名类型，play-播放域名，image-封面域名
     *
     * Generated from protobuf field <code>string DomainType = 3;</code>
     * @return string
     */
    public function getDomainType()
    {
        return $this->DomainType;
    }

    /**
     *域名类型，play-播放域名，image-封面域名
     *
     * Generated from protobuf field <code>string DomainType = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDomainType($var)
    {
        GPBUtil::checkString($var, True);
        $this->DomainType = $var;

        return $this;
    }

    /**
     *源站类型
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.SourceStationType SourceStationType = 4;</code>
     * @return int
     */
    public function getSourceStationType()
    {
        return $this->SourceStationType;
    }

    /**
     *源站类型
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.SourceStationType SourceStationType = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSourceStationType($var)
    {
        GPBUtil::checkEnum($var, \Byteplus\Service\Vod\Models\Business\SourceStationType::class);
        $this->SourceStationType = $var;

        return $this;
    }

    /**
     *签算类型
     *
     * Generated from protobuf field <code>string AuthType = 5;</code>
     * @return string
     */
    public function getAuthType()
    {
        return $this->AuthType;
    }

    /**
     *签算类型
     *
     * Generated from protobuf field <code>string AuthType = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthType($var)
    {
        GPBUtil::checkString($var, True);
        $this->AuthType = $var;

        return $this;
    }

}

