<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.CacheKeyAction</code>
 */
class CacheKeyAction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.CacheKeyComponents CacheKeyComponents = 2;</code>
     */
    private $CacheKeyComponents;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\CacheKeyComponents[]|\Google\Protobuf\Internal\RepeatedField $CacheKeyComponents
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.CacheKeyComponents CacheKeyComponents = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCacheKeyComponents()
    {
        return $this->CacheKeyComponents;
    }

    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.CacheKeyComponents CacheKeyComponents = 2;</code>
     * @param \Byteplus\Service\Vod\Models\Business\CacheKeyComponents[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCacheKeyComponents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Byteplus\Service\Vod\Models\Business\CacheKeyComponents::class);
        $this->CacheKeyComponents = $arr;

        return $this;
    }

}

