<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.CdnConfig</code>
 */
class CdnConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Domain = 1;</code>
     */
    protected $Domain = '';
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.Origin Origin = 2;</code>
     */
    protected $Origin = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.OriginHost OriginHost = 3;</code>
     */
    protected $OriginHost = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.RefererControl RefererControl = 4;</code>
     */
    protected $RefererControl = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.IpControl IpControl = 5;</code>
     */
    protected $IpControl = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.ExpireControl ExpireControl = 6;</code>
     */
    protected $ExpireControl = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.DomainAuthInfo AuthInfo = 7;</code>
     */
    protected $AuthInfo = null;
    /**
     * Generated from protobuf field <code>string OriginProtocol = 8;</code>
     */
    protected $OriginProtocol = '';
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.OriginSniControl OriginSniControl = 9;</code>
     */
    protected $OriginSniControl = null;
    /**
     * Generated from protobuf field <code>bool FollowRedirect = 10;</code>
     */
    protected $FollowRedirect = false;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.TimeOutControl TimeOutControl = 11;</code>
     */
    protected $TimeOutControl = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.RequestHeaderControl RequestHeaderControl = 12;</code>
     */
    protected $RequestHeaderControl = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.OriginArgControl OriginArgControl = 13;</code>
     */
    protected $OriginArgControl = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.ResponseHeaderControl ResponseHeaderControl = 14;</code>
     */
    protected $ResponseHeaderControl = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.CacheControl CacheControl = 15;</code>
     */
    protected $CacheControl = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.CacheKeyControl CacheKeyControl = 16;</code>
     */
    protected $CacheKeyControl = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.NegativeCacheControl NegativeCacheControl = 17;</code>
     */
    protected $NegativeCacheControl = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.HTTPSControl HTTPSControl = 18;</code>
     */
    protected $HTTPSControl = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.HttpForcedRedirectControl HttpForcedRedirectControl = 19;</code>
     */
    protected $HttpForcedRedirectControl = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.CompressionRulesControl CompressionRulesControl = 20;</code>
     */
    protected $CompressionRulesControl = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VideoDragControl VideoDragControl = 21;</code>
     */
    protected $VideoDragControl = null;
    /**
     * URL 鉴权配置模块
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.SignedUrlAuthControl SignedUrlAuthControl = 22;</code>
     */
    protected $SignedUrlAuthControl = null;
    /**
     * UA 黑白名单配置模块
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.UaAccessRuleControl UaAccessRuleControl = 23;</code>
     */
    protected $UaAccessRuleControl = null;
    /**
     *远程鉴权配置模块
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.RemoteAuthControl RemoteAuthControl = 24;</code>
     */
    protected $RemoteAuthControl = null;
    /**
     *地域访问限制配置模块
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.AreaAccessRuleControl AreaAccessRuleControl = 25;</code>
     */
    protected $AreaAccessRuleControl = null;
    /**
     *禁用 HTTP Method 配置模块
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.MethodDeniedRuleControl MethodDeniedRuleControl = 26;</code>
     */
    protected $MethodDeniedRuleControl = null;
    /**
     *下载限速配置模块
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.DownloadSpeedLimitControl DownloadSpeedLimitControl = 27;</code>
     */
    protected $DownloadSpeedLimitControl = null;
    /**
     * Origin防盗链
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.OriginAccessRuleControl OriginAccessRuleControl = 28;</code>
     */
    protected $OriginAccessRuleControl = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.RewriteHLS RewriteHLS = 29;</code>
     */
    protected $RewriteHLS = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Domain
     *     @type \Byteplus\Service\Vod\Models\Business\Origin $Origin
     *     @type \Byteplus\Service\Vod\Models\Business\OriginHost $OriginHost
     *     @type \Byteplus\Service\Vod\Models\Business\RefererControl $RefererControl
     *     @type \Byteplus\Service\Vod\Models\Business\IpControl $IpControl
     *     @type \Byteplus\Service\Vod\Models\Business\ExpireControl $ExpireControl
     *     @type \Byteplus\Service\Vod\Models\Business\DomainAuthInfo $AuthInfo
     *     @type string $OriginProtocol
     *     @type \Byteplus\Service\Vod\Models\Business\OriginSniControl $OriginSniControl
     *     @type bool $FollowRedirect
     *     @type \Byteplus\Service\Vod\Models\Business\TimeOutControl $TimeOutControl
     *     @type \Byteplus\Service\Vod\Models\Business\RequestHeaderControl $RequestHeaderControl
     *     @type \Byteplus\Service\Vod\Models\Business\OriginArgControl $OriginArgControl
     *     @type \Byteplus\Service\Vod\Models\Business\ResponseHeaderControl $ResponseHeaderControl
     *     @type \Byteplus\Service\Vod\Models\Business\CacheControl $CacheControl
     *     @type \Byteplus\Service\Vod\Models\Business\CacheKeyControl $CacheKeyControl
     *     @type \Byteplus\Service\Vod\Models\Business\NegativeCacheControl $NegativeCacheControl
     *     @type \Byteplus\Service\Vod\Models\Business\HTTPSControl $HTTPSControl
     *     @type \Byteplus\Service\Vod\Models\Business\HttpForcedRedirectControl $HttpForcedRedirectControl
     *     @type \Byteplus\Service\Vod\Models\Business\CompressionRulesControl $CompressionRulesControl
     *     @type \Byteplus\Service\Vod\Models\Business\VideoDragControl $VideoDragControl
     *     @type \Byteplus\Service\Vod\Models\Business\SignedUrlAuthControl $SignedUrlAuthControl
     *           URL 鉴权配置模块
     *     @type \Byteplus\Service\Vod\Models\Business\UaAccessRuleControl $UaAccessRuleControl
     *           UA 黑白名单配置模块
     *     @type \Byteplus\Service\Vod\Models\Business\RemoteAuthControl $RemoteAuthControl
     *          远程鉴权配置模块
     *     @type \Byteplus\Service\Vod\Models\Business\AreaAccessRuleControl $AreaAccessRuleControl
     *          地域访问限制配置模块
     *     @type \Byteplus\Service\Vod\Models\Business\MethodDeniedRuleControl $MethodDeniedRuleControl
     *          禁用 HTTP Method 配置模块
     *     @type \Byteplus\Service\Vod\Models\Business\DownloadSpeedLimitControl $DownloadSpeedLimitControl
     *          下载限速配置模块
     *     @type \Byteplus\Service\Vod\Models\Business\OriginAccessRuleControl $OriginAccessRuleControl
     *           Origin防盗链
     *     @type \Byteplus\Service\Vod\Models\Business\RewriteHLS $RewriteHLS
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Domain = 1;</code>
     * @return string
     */
    public function getDomain()
    {
        return $this->Domain;
    }

    /**
     * Generated from protobuf field <code>string Domain = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDomain($var)
    {
        GPBUtil::checkString($var, True);
        $this->Domain = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.Origin Origin = 2;</code>
     * @return \Byteplus\Service\Vod\Models\Business\Origin|null
     */
    public function getOrigin()
    {
        return $this->Origin;
    }

    public function hasOrigin()
    {
        return isset($this->Origin);
    }

    public function clearOrigin()
    {
        unset($this->Origin);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.Origin Origin = 2;</code>
     * @param \Byteplus\Service\Vod\Models\Business\Origin $var
     * @return $this
     */
    public function setOrigin($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\Origin::class);
        $this->Origin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.OriginHost OriginHost = 3;</code>
     * @return \Byteplus\Service\Vod\Models\Business\OriginHost|null
     */
    public function getOriginHost()
    {
        return $this->OriginHost;
    }

    public function hasOriginHost()
    {
        return isset($this->OriginHost);
    }

    public function clearOriginHost()
    {
        unset($this->OriginHost);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.OriginHost OriginHost = 3;</code>
     * @param \Byteplus\Service\Vod\Models\Business\OriginHost $var
     * @return $this
     */
    public function setOriginHost($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\OriginHost::class);
        $this->OriginHost = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.RefererControl RefererControl = 4;</code>
     * @return \Byteplus\Service\Vod\Models\Business\RefererControl|null
     */
    public function getRefererControl()
    {
        return $this->RefererControl;
    }

    public function hasRefererControl()
    {
        return isset($this->RefererControl);
    }

    public function clearRefererControl()
    {
        unset($this->RefererControl);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.RefererControl RefererControl = 4;</code>
     * @param \Byteplus\Service\Vod\Models\Business\RefererControl $var
     * @return $this
     */
    public function setRefererControl($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\RefererControl::class);
        $this->RefererControl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.IpControl IpControl = 5;</code>
     * @return \Byteplus\Service\Vod\Models\Business\IpControl|null
     */
    public function getIpControl()
    {
        return $this->IpControl;
    }

    public function hasIpControl()
    {
        return isset($this->IpControl);
    }

    public function clearIpControl()
    {
        unset($this->IpControl);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.IpControl IpControl = 5;</code>
     * @param \Byteplus\Service\Vod\Models\Business\IpControl $var
     * @return $this
     */
    public function setIpControl($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\IpControl::class);
        $this->IpControl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.ExpireControl ExpireControl = 6;</code>
     * @return \Byteplus\Service\Vod\Models\Business\ExpireControl|null
     */
    public function getExpireControl()
    {
        return $this->ExpireControl;
    }

    public function hasExpireControl()
    {
        return isset($this->ExpireControl);
    }

    public function clearExpireControl()
    {
        unset($this->ExpireControl);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.ExpireControl ExpireControl = 6;</code>
     * @param \Byteplus\Service\Vod\Models\Business\ExpireControl $var
     * @return $this
     */
    public function setExpireControl($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\ExpireControl::class);
        $this->ExpireControl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.DomainAuthInfo AuthInfo = 7;</code>
     * @return \Byteplus\Service\Vod\Models\Business\DomainAuthInfo|null
     */
    public function getAuthInfo()
    {
        return $this->AuthInfo;
    }

    public function hasAuthInfo()
    {
        return isset($this->AuthInfo);
    }

    public function clearAuthInfo()
    {
        unset($this->AuthInfo);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.DomainAuthInfo AuthInfo = 7;</code>
     * @param \Byteplus\Service\Vod\Models\Business\DomainAuthInfo $var
     * @return $this
     */
    public function setAuthInfo($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\DomainAuthInfo::class);
        $this->AuthInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string OriginProtocol = 8;</code>
     * @return string
     */
    public function getOriginProtocol()
    {
        return $this->OriginProtocol;
    }

    /**
     * Generated from protobuf field <code>string OriginProtocol = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setOriginProtocol($var)
    {
        GPBUtil::checkString($var, True);
        $this->OriginProtocol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.OriginSniControl OriginSniControl = 9;</code>
     * @return \Byteplus\Service\Vod\Models\Business\OriginSniControl|null
     */
    public function getOriginSniControl()
    {
        return $this->OriginSniControl;
    }

    public function hasOriginSniControl()
    {
        return isset($this->OriginSniControl);
    }

    public function clearOriginSniControl()
    {
        unset($this->OriginSniControl);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.OriginSniControl OriginSniControl = 9;</code>
     * @param \Byteplus\Service\Vod\Models\Business\OriginSniControl $var
     * @return $this
     */
    public function setOriginSniControl($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\OriginSniControl::class);
        $this->OriginSniControl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool FollowRedirect = 10;</code>
     * @return bool
     */
    public function getFollowRedirect()
    {
        return $this->FollowRedirect;
    }

    /**
     * Generated from protobuf field <code>bool FollowRedirect = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setFollowRedirect($var)
    {
        GPBUtil::checkBool($var);
        $this->FollowRedirect = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.TimeOutControl TimeOutControl = 11;</code>
     * @return \Byteplus\Service\Vod\Models\Business\TimeOutControl|null
     */
    public function getTimeOutControl()
    {
        return $this->TimeOutControl;
    }

    public function hasTimeOutControl()
    {
        return isset($this->TimeOutControl);
    }

    public function clearTimeOutControl()
    {
        unset($this->TimeOutControl);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.TimeOutControl TimeOutControl = 11;</code>
     * @param \Byteplus\Service\Vod\Models\Business\TimeOutControl $var
     * @return $this
     */
    public function setTimeOutControl($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\TimeOutControl::class);
        $this->TimeOutControl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.RequestHeaderControl RequestHeaderControl = 12;</code>
     * @return \Byteplus\Service\Vod\Models\Business\RequestHeaderControl|null
     */
    public function getRequestHeaderControl()
    {
        return $this->RequestHeaderControl;
    }

    public function hasRequestHeaderControl()
    {
        return isset($this->RequestHeaderControl);
    }

    public function clearRequestHeaderControl()
    {
        unset($this->RequestHeaderControl);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.RequestHeaderControl RequestHeaderControl = 12;</code>
     * @param \Byteplus\Service\Vod\Models\Business\RequestHeaderControl $var
     * @return $this
     */
    public function setRequestHeaderControl($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\RequestHeaderControl::class);
        $this->RequestHeaderControl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.OriginArgControl OriginArgControl = 13;</code>
     * @return \Byteplus\Service\Vod\Models\Business\OriginArgControl|null
     */
    public function getOriginArgControl()
    {
        return $this->OriginArgControl;
    }

    public function hasOriginArgControl()
    {
        return isset($this->OriginArgControl);
    }

    public function clearOriginArgControl()
    {
        unset($this->OriginArgControl);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.OriginArgControl OriginArgControl = 13;</code>
     * @param \Byteplus\Service\Vod\Models\Business\OriginArgControl $var
     * @return $this
     */
    public function setOriginArgControl($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\OriginArgControl::class);
        $this->OriginArgControl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.ResponseHeaderControl ResponseHeaderControl = 14;</code>
     * @return \Byteplus\Service\Vod\Models\Business\ResponseHeaderControl|null
     */
    public function getResponseHeaderControl()
    {
        return $this->ResponseHeaderControl;
    }

    public function hasResponseHeaderControl()
    {
        return isset($this->ResponseHeaderControl);
    }

    public function clearResponseHeaderControl()
    {
        unset($this->ResponseHeaderControl);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.ResponseHeaderControl ResponseHeaderControl = 14;</code>
     * @param \Byteplus\Service\Vod\Models\Business\ResponseHeaderControl $var
     * @return $this
     */
    public function setResponseHeaderControl($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\ResponseHeaderControl::class);
        $this->ResponseHeaderControl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.CacheControl CacheControl = 15;</code>
     * @return \Byteplus\Service\Vod\Models\Business\CacheControl|null
     */
    public function getCacheControl()
    {
        return $this->CacheControl;
    }

    public function hasCacheControl()
    {
        return isset($this->CacheControl);
    }

    public function clearCacheControl()
    {
        unset($this->CacheControl);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.CacheControl CacheControl = 15;</code>
     * @param \Byteplus\Service\Vod\Models\Business\CacheControl $var
     * @return $this
     */
    public function setCacheControl($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\CacheControl::class);
        $this->CacheControl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.CacheKeyControl CacheKeyControl = 16;</code>
     * @return \Byteplus\Service\Vod\Models\Business\CacheKeyControl|null
     */
    public function getCacheKeyControl()
    {
        return $this->CacheKeyControl;
    }

    public function hasCacheKeyControl()
    {
        return isset($this->CacheKeyControl);
    }

    public function clearCacheKeyControl()
    {
        unset($this->CacheKeyControl);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.CacheKeyControl CacheKeyControl = 16;</code>
     * @param \Byteplus\Service\Vod\Models\Business\CacheKeyControl $var
     * @return $this
     */
    public function setCacheKeyControl($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\CacheKeyControl::class);
        $this->CacheKeyControl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.NegativeCacheControl NegativeCacheControl = 17;</code>
     * @return \Byteplus\Service\Vod\Models\Business\NegativeCacheControl|null
     */
    public function getNegativeCacheControl()
    {
        return $this->NegativeCacheControl;
    }

    public function hasNegativeCacheControl()
    {
        return isset($this->NegativeCacheControl);
    }

    public function clearNegativeCacheControl()
    {
        unset($this->NegativeCacheControl);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.NegativeCacheControl NegativeCacheControl = 17;</code>
     * @param \Byteplus\Service\Vod\Models\Business\NegativeCacheControl $var
     * @return $this
     */
    public function setNegativeCacheControl($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\NegativeCacheControl::class);
        $this->NegativeCacheControl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.HTTPSControl HTTPSControl = 18;</code>
     * @return \Byteplus\Service\Vod\Models\Business\HTTPSControl|null
     */
    public function getHTTPSControl()
    {
        return $this->HTTPSControl;
    }

    public function hasHTTPSControl()
    {
        return isset($this->HTTPSControl);
    }

    public function clearHTTPSControl()
    {
        unset($this->HTTPSControl);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.HTTPSControl HTTPSControl = 18;</code>
     * @param \Byteplus\Service\Vod\Models\Business\HTTPSControl $var
     * @return $this
     */
    public function setHTTPSControl($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\HTTPSControl::class);
        $this->HTTPSControl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.HttpForcedRedirectControl HttpForcedRedirectControl = 19;</code>
     * @return \Byteplus\Service\Vod\Models\Business\HttpForcedRedirectControl|null
     */
    public function getHttpForcedRedirectControl()
    {
        return $this->HttpForcedRedirectControl;
    }

    public function hasHttpForcedRedirectControl()
    {
        return isset($this->HttpForcedRedirectControl);
    }

    public function clearHttpForcedRedirectControl()
    {
        unset($this->HttpForcedRedirectControl);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.HttpForcedRedirectControl HttpForcedRedirectControl = 19;</code>
     * @param \Byteplus\Service\Vod\Models\Business\HttpForcedRedirectControl $var
     * @return $this
     */
    public function setHttpForcedRedirectControl($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\HttpForcedRedirectControl::class);
        $this->HttpForcedRedirectControl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.CompressionRulesControl CompressionRulesControl = 20;</code>
     * @return \Byteplus\Service\Vod\Models\Business\CompressionRulesControl|null
     */
    public function getCompressionRulesControl()
    {
        return $this->CompressionRulesControl;
    }

    public function hasCompressionRulesControl()
    {
        return isset($this->CompressionRulesControl);
    }

    public function clearCompressionRulesControl()
    {
        unset($this->CompressionRulesControl);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.CompressionRulesControl CompressionRulesControl = 20;</code>
     * @param \Byteplus\Service\Vod\Models\Business\CompressionRulesControl $var
     * @return $this
     */
    public function setCompressionRulesControl($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\CompressionRulesControl::class);
        $this->CompressionRulesControl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VideoDragControl VideoDragControl = 21;</code>
     * @return \Byteplus\Service\Vod\Models\Business\VideoDragControl|null
     */
    public function getVideoDragControl()
    {
        return $this->VideoDragControl;
    }

    public function hasVideoDragControl()
    {
        return isset($this->VideoDragControl);
    }

    public function clearVideoDragControl()
    {
        unset($this->VideoDragControl);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VideoDragControl VideoDragControl = 21;</code>
     * @param \Byteplus\Service\Vod\Models\Business\VideoDragControl $var
     * @return $this
     */
    public function setVideoDragControl($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\VideoDragControl::class);
        $this->VideoDragControl = $var;

        return $this;
    }

    /**
     * URL 鉴权配置模块
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.SignedUrlAuthControl SignedUrlAuthControl = 22;</code>
     * @return \Byteplus\Service\Vod\Models\Business\SignedUrlAuthControl|null
     */
    public function getSignedUrlAuthControl()
    {
        return $this->SignedUrlAuthControl;
    }

    public function hasSignedUrlAuthControl()
    {
        return isset($this->SignedUrlAuthControl);
    }

    public function clearSignedUrlAuthControl()
    {
        unset($this->SignedUrlAuthControl);
    }

    /**
     * URL 鉴权配置模块
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.SignedUrlAuthControl SignedUrlAuthControl = 22;</code>
     * @param \Byteplus\Service\Vod\Models\Business\SignedUrlAuthControl $var
     * @return $this
     */
    public function setSignedUrlAuthControl($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\SignedUrlAuthControl::class);
        $this->SignedUrlAuthControl = $var;

        return $this;
    }

    /**
     * UA 黑白名单配置模块
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.UaAccessRuleControl UaAccessRuleControl = 23;</code>
     * @return \Byteplus\Service\Vod\Models\Business\UaAccessRuleControl|null
     */
    public function getUaAccessRuleControl()
    {
        return $this->UaAccessRuleControl;
    }

    public function hasUaAccessRuleControl()
    {
        return isset($this->UaAccessRuleControl);
    }

    public function clearUaAccessRuleControl()
    {
        unset($this->UaAccessRuleControl);
    }

    /**
     * UA 黑白名单配置模块
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.UaAccessRuleControl UaAccessRuleControl = 23;</code>
     * @param \Byteplus\Service\Vod\Models\Business\UaAccessRuleControl $var
     * @return $this
     */
    public function setUaAccessRuleControl($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\UaAccessRuleControl::class);
        $this->UaAccessRuleControl = $var;

        return $this;
    }

    /**
     *远程鉴权配置模块
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.RemoteAuthControl RemoteAuthControl = 24;</code>
     * @return \Byteplus\Service\Vod\Models\Business\RemoteAuthControl|null
     */
    public function getRemoteAuthControl()
    {
        return $this->RemoteAuthControl;
    }

    public function hasRemoteAuthControl()
    {
        return isset($this->RemoteAuthControl);
    }

    public function clearRemoteAuthControl()
    {
        unset($this->RemoteAuthControl);
    }

    /**
     *远程鉴权配置模块
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.RemoteAuthControl RemoteAuthControl = 24;</code>
     * @param \Byteplus\Service\Vod\Models\Business\RemoteAuthControl $var
     * @return $this
     */
    public function setRemoteAuthControl($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\RemoteAuthControl::class);
        $this->RemoteAuthControl = $var;

        return $this;
    }

    /**
     *地域访问限制配置模块
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.AreaAccessRuleControl AreaAccessRuleControl = 25;</code>
     * @return \Byteplus\Service\Vod\Models\Business\AreaAccessRuleControl|null
     */
    public function getAreaAccessRuleControl()
    {
        return $this->AreaAccessRuleControl;
    }

    public function hasAreaAccessRuleControl()
    {
        return isset($this->AreaAccessRuleControl);
    }

    public function clearAreaAccessRuleControl()
    {
        unset($this->AreaAccessRuleControl);
    }

    /**
     *地域访问限制配置模块
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.AreaAccessRuleControl AreaAccessRuleControl = 25;</code>
     * @param \Byteplus\Service\Vod\Models\Business\AreaAccessRuleControl $var
     * @return $this
     */
    public function setAreaAccessRuleControl($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\AreaAccessRuleControl::class);
        $this->AreaAccessRuleControl = $var;

        return $this;
    }

    /**
     *禁用 HTTP Method 配置模块
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.MethodDeniedRuleControl MethodDeniedRuleControl = 26;</code>
     * @return \Byteplus\Service\Vod\Models\Business\MethodDeniedRuleControl|null
     */
    public function getMethodDeniedRuleControl()
    {
        return $this->MethodDeniedRuleControl;
    }

    public function hasMethodDeniedRuleControl()
    {
        return isset($this->MethodDeniedRuleControl);
    }

    public function clearMethodDeniedRuleControl()
    {
        unset($this->MethodDeniedRuleControl);
    }

    /**
     *禁用 HTTP Method 配置模块
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.MethodDeniedRuleControl MethodDeniedRuleControl = 26;</code>
     * @param \Byteplus\Service\Vod\Models\Business\MethodDeniedRuleControl $var
     * @return $this
     */
    public function setMethodDeniedRuleControl($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\MethodDeniedRuleControl::class);
        $this->MethodDeniedRuleControl = $var;

        return $this;
    }

    /**
     *下载限速配置模块
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.DownloadSpeedLimitControl DownloadSpeedLimitControl = 27;</code>
     * @return \Byteplus\Service\Vod\Models\Business\DownloadSpeedLimitControl|null
     */
    public function getDownloadSpeedLimitControl()
    {
        return $this->DownloadSpeedLimitControl;
    }

    public function hasDownloadSpeedLimitControl()
    {
        return isset($this->DownloadSpeedLimitControl);
    }

    public function clearDownloadSpeedLimitControl()
    {
        unset($this->DownloadSpeedLimitControl);
    }

    /**
     *下载限速配置模块
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.DownloadSpeedLimitControl DownloadSpeedLimitControl = 27;</code>
     * @param \Byteplus\Service\Vod\Models\Business\DownloadSpeedLimitControl $var
     * @return $this
     */
    public function setDownloadSpeedLimitControl($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\DownloadSpeedLimitControl::class);
        $this->DownloadSpeedLimitControl = $var;

        return $this;
    }

    /**
     * Origin防盗链
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.OriginAccessRuleControl OriginAccessRuleControl = 28;</code>
     * @return \Byteplus\Service\Vod\Models\Business\OriginAccessRuleControl|null
     */
    public function getOriginAccessRuleControl()
    {
        return $this->OriginAccessRuleControl;
    }

    public function hasOriginAccessRuleControl()
    {
        return isset($this->OriginAccessRuleControl);
    }

    public function clearOriginAccessRuleControl()
    {
        unset($this->OriginAccessRuleControl);
    }

    /**
     * Origin防盗链
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.OriginAccessRuleControl OriginAccessRuleControl = 28;</code>
     * @param \Byteplus\Service\Vod\Models\Business\OriginAccessRuleControl $var
     * @return $this
     */
    public function setOriginAccessRuleControl($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\OriginAccessRuleControl::class);
        $this->OriginAccessRuleControl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.RewriteHLS RewriteHLS = 29;</code>
     * @return \Byteplus\Service\Vod\Models\Business\RewriteHLS|null
     */
    public function getRewriteHLS()
    {
        return $this->RewriteHLS;
    }

    public function hasRewriteHLS()
    {
        return isset($this->RewriteHLS);
    }

    public function clearRewriteHLS()
    {
        unset($this->RewriteHLS);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.RewriteHLS RewriteHLS = 29;</code>
     * @param \Byteplus\Service\Vod\Models\Business\RewriteHLS $var
     * @return $this
     */
    public function setRewriteHLS($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\RewriteHLS::class);
        $this->RewriteHLS = $var;

        return $this;
    }

}

