<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.CdnStatusData</code>
 */
class CdnStatusData extends \Google\Protobuf\Internal\Message
{
    /**
     * 请求数
     *
     * Generated from protobuf field <code>int64 Conn = 1;</code>
     */
    protected $Conn = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $Conn
     *           请求数
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * 请求数
     *
     * Generated from protobuf field <code>int64 Conn = 1;</code>
     * @return int|string
     */
    public function getConn()
    {
        return $this->Conn;
    }

    /**
     * 请求数
     *
     * Generated from protobuf field <code>int64 Conn = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setConn($var)
    {
        GPBUtil::checkInt64($var);
        $this->Conn = $var;

        return $this;
    }

}

