<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.CompressionRule</code>
 */
class CompressionRule extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.Condition Condition = 1;</code>
     */
    protected $Condition = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.CompressionAction CompressionAction = 2;</code>
     */
    protected $CompressionAction = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\Condition $Condition
     *     @type \Byteplus\Service\Vod\Models\Business\CompressionAction $CompressionAction
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.Condition Condition = 1;</code>
     * @return \Byteplus\Service\Vod\Models\Business\Condition|null
     */
    public function getCondition()
    {
        return $this->Condition;
    }

    public function hasCondition()
    {
        return isset($this->Condition);
    }

    public function clearCondition()
    {
        unset($this->Condition);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.Condition Condition = 1;</code>
     * @param \Byteplus\Service\Vod\Models\Business\Condition $var
     * @return $this
     */
    public function setCondition($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\Condition::class);
        $this->Condition = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.CompressionAction CompressionAction = 2;</code>
     * @return \Byteplus\Service\Vod\Models\Business\CompressionAction|null
     */
    public function getCompressionAction()
    {
        return $this->CompressionAction;
    }

    public function hasCompressionAction()
    {
        return isset($this->CompressionAction);
    }

    public function clearCompressionAction()
    {
        unset($this->CompressionAction);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.CompressionAction CompressionAction = 2;</code>
     * @param \Byteplus\Service\Vod\Models\Business\CompressionAction $var
     * @return $this
     */
    public function setCompressionAction($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\CompressionAction::class);
        $this->CompressionAction = $var;

        return $this;
    }

}

