<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.Condition</code>
 */
class Condition extends \Google\Protobuf\Internal\Message
{
    /**
     *
     * Generated from protobuf field <code>string Connective = 1;</code>
     */
    protected $Connective = '';
    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.ConditionRule ConditionRule = 2;</code>
     */
    private $ConditionRule;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Connective
     *     @type \Byteplus\Service\Vod\Models\Business\ConditionRule[]|\Google\Protobuf\Internal\RepeatedField $ConditionRule
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     *
     * Generated from protobuf field <code>string Connective = 1;</code>
     * @return string
     */
    public function getConnective()
    {
        return $this->Connective;
    }

    /**
     *
     * Generated from protobuf field <code>string Connective = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setConnective($var)
    {
        GPBUtil::checkString($var, True);
        $this->Connective = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.ConditionRule ConditionRule = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConditionRule()
    {
        return $this->ConditionRule;
    }

    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.ConditionRule ConditionRule = 2;</code>
     * @param \Byteplus\Service\Vod\Models\Business\ConditionRule[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConditionRule($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Byteplus\Service\Vod\Models\Business\ConditionRule::class);
        $this->ConditionRule = $arr;

        return $this;
    }

}

