<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.CustomVariableInstance</code>
 */
class CustomVariableInstance extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Operator = 1;</code>
     */
    protected $Operator = '';
    /**
     * Generated from protobuf field <code>string Type = 2;</code>
     */
    protected $Type = '';
    /**
     * Generated from protobuf field <code>string Value = 3;</code>
     */
    protected $Value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Operator
     *     @type string $Type
     *     @type string $Value
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Operator = 1;</code>
     * @return string
     */
    public function getOperator()
    {
        return $this->Operator;
    }

    /**
     * Generated from protobuf field <code>string Operator = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOperator($var)
    {
        GPBUtil::checkString($var, True);
        $this->Operator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Type = 2;</code>
     * @return string
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * Generated from protobuf field <code>string Type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->Type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Value = 3;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->Value;
    }

    /**
     * Generated from protobuf field <code>string Value = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->Value = $var;

        return $this;
    }

}

