<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.CustomVariableRules</code>
 */
class CustomVariableRules extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.CustomVariableInstance CustomVariableInstances = 1;</code>
     */
    private $CustomVariableInstances;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\CustomVariableInstance[]|\Google\Protobuf\Internal\RepeatedField $CustomVariableInstances
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.CustomVariableInstance CustomVariableInstances = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCustomVariableInstances()
    {
        return $this->CustomVariableInstances;
    }

    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.CustomVariableInstance CustomVariableInstances = 1;</code>
     * @param \Byteplus\Service\Vod\Models\Business\CustomVariableInstance[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCustomVariableInstances($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Byteplus\Service\Vod\Models\Business\CustomVariableInstance::class);
        $this->CustomVariableInstances = $arr;

        return $this;
    }

}

