<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_measure.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.DescribeVodSpaceStorageDataFDResult</code>
 */
class DescribeVodSpaceStorageDataFDResult extends \Google\Protobuf\Internal\Message
{
    /**
     * 空间列表
     *
     * Generated from protobuf field <code>repeated string SpaceList = 1;</code>
     */
    private $SpaceList;
    /**
     * 查询的起始时间, rfc3339
     *
     * Generated from protobuf field <code>string StartTime = 2;</code>
     */
    protected $StartTime = '';
    /**
     * 查询的结束时间, rfc3339；查询时间跨度不超过31天
     *
     * Generated from protobuf field <code>string EndTime = 3;</code>
     */
    protected $EndTime = '';
    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.DescribeVodSpaceStorageDataFDItem StorageDataList = 4;</code>
     */
    private $StorageDataList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $SpaceList
     *           空间列表
     *     @type string $StartTime
     *           查询的起始时间, rfc3339
     *     @type string $EndTime
     *           查询的结束时间, rfc3339；查询时间跨度不超过31天
     *     @type \Byteplus\Service\Vod\Models\Business\DescribeVodSpaceStorageDataFDItem[]|\Google\Protobuf\Internal\RepeatedField $StorageDataList
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodMeasure::initOnce();
        parent::__construct($data);
    }

    /**
     * 空间列表
     *
     * Generated from protobuf field <code>repeated string SpaceList = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpaceList()
    {
        return $this->SpaceList;
    }

    /**
     * 空间列表
     *
     * Generated from protobuf field <code>repeated string SpaceList = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpaceList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->SpaceList = $arr;

        return $this;
    }

    /**
     * 查询的起始时间, rfc3339
     *
     * Generated from protobuf field <code>string StartTime = 2;</code>
     * @return string
     */
    public function getStartTime()
    {
        return $this->StartTime;
    }

    /**
     * 查询的起始时间, rfc3339
     *
     * Generated from protobuf field <code>string StartTime = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->StartTime = $var;

        return $this;
    }

    /**
     * 查询的结束时间, rfc3339；查询时间跨度不超过31天
     *
     * Generated from protobuf field <code>string EndTime = 3;</code>
     * @return string
     */
    public function getEndTime()
    {
        return $this->EndTime;
    }

    /**
     * 查询的结束时间, rfc3339；查询时间跨度不超过31天
     *
     * Generated from protobuf field <code>string EndTime = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->EndTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.DescribeVodSpaceStorageDataFDItem StorageDataList = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStorageDataList()
    {
        return $this->StorageDataList;
    }

    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.DescribeVodSpaceStorageDataFDItem StorageDataList = 4;</code>
     * @param \Byteplus\Service\Vod\Models\Business\DescribeVodSpaceStorageDataFDItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStorageDataList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Byteplus\Service\Vod\Models\Business\DescribeVodSpaceStorageDataFDItem::class);
        $this->StorageDataList = $arr;

        return $this;
    }

}

