<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.DownloadSpeedLimitAction</code>
 */
class DownloadSpeedLimitAction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double SpeedLimitRate = 1;</code>
     */
    protected $SpeedLimitRate = 0.0;
    /**
     * Generated from protobuf field <code>double SpeedLimitRateAfter = 2;</code>
     */
    protected $SpeedLimitRateAfter = 0.0;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.SpeedLimitTime SpeedLimitTime = 3;</code>
     */
    protected $SpeedLimitTime = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $SpeedLimitRate
     *     @type float $SpeedLimitRateAfter
     *     @type \Byteplus\Service\Vod\Models\Business\SpeedLimitTime $SpeedLimitTime
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double SpeedLimitRate = 1;</code>
     * @return float
     */
    public function getSpeedLimitRate()
    {
        return $this->SpeedLimitRate;
    }

    /**
     * Generated from protobuf field <code>double SpeedLimitRate = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setSpeedLimitRate($var)
    {
        GPBUtil::checkDouble($var);
        $this->SpeedLimitRate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double SpeedLimitRateAfter = 2;</code>
     * @return float
     */
    public function getSpeedLimitRateAfter()
    {
        return $this->SpeedLimitRateAfter;
    }

    /**
     * Generated from protobuf field <code>double SpeedLimitRateAfter = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setSpeedLimitRateAfter($var)
    {
        GPBUtil::checkDouble($var);
        $this->SpeedLimitRateAfter = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.SpeedLimitTime SpeedLimitTime = 3;</code>
     * @return \Byteplus\Service\Vod\Models\Business\SpeedLimitTime|null
     */
    public function getSpeedLimitTime()
    {
        return $this->SpeedLimitTime;
    }

    public function hasSpeedLimitTime()
    {
        return isset($this->SpeedLimitTime);
    }

    public function clearSpeedLimitTime()
    {
        unset($this->SpeedLimitTime);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.SpeedLimitTime SpeedLimitTime = 3;</code>
     * @param \Byteplus\Service\Vod\Models\Business\SpeedLimitTime $var
     * @return $this
     */
    public function setSpeedLimitTime($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\SpeedLimitTime::class);
        $this->SpeedLimitTime = $var;

        return $this;
    }

}

