<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * http->https
 *
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.ForcedRedirect</code>
 */
class ForcedRedirect extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool EnableForcedRedirect = 1;</code>
     */
    protected $EnableForcedRedirect = false;
    /**
     * Generated from protobuf field <code>string StatusCode = 2;</code>
     */
    protected $StatusCode = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $EnableForcedRedirect
     *     @type string $StatusCode
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool EnableForcedRedirect = 1;</code>
     * @return bool
     */
    public function getEnableForcedRedirect()
    {
        return $this->EnableForcedRedirect;
    }

    /**
     * Generated from protobuf field <code>bool EnableForcedRedirect = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableForcedRedirect($var)
    {
        GPBUtil::checkBool($var);
        $this->EnableForcedRedirect = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string StatusCode = 2;</code>
     * @return string
     */
    public function getStatusCode()
    {
        return $this->StatusCode;
    }

    /**
     * Generated from protobuf field <code>string StatusCode = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStatusCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->StatusCode = $var;

        return $this;
    }

}

