<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.Hsts</code>
 */
class Hsts extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double Ttl = 1;</code>
     */
    protected $Ttl = 0.0;
    /**
     * Generated from protobuf field <code>string Subdomain = 2;</code>
     */
    protected $Subdomain = '';
    /**
     * Generated from protobuf field <code>bool Switch = 3;</code>
     */
    protected $Switch = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $Ttl
     *     @type string $Subdomain
     *     @type bool $Switch
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double Ttl = 1;</code>
     * @return float
     */
    public function getTtl()
    {
        return $this->Ttl;
    }

    /**
     * Generated from protobuf field <code>double Ttl = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setTtl($var)
    {
        GPBUtil::checkDouble($var);
        $this->Ttl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Subdomain = 2;</code>
     * @return string
     */
    public function getSubdomain()
    {
        return $this->Subdomain;
    }

    /**
     * Generated from protobuf field <code>string Subdomain = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSubdomain($var)
    {
        GPBUtil::checkString($var, True);
        $this->Subdomain = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool Switch = 3;</code>
     * @return bool
     */
    public function getSwitch()
    {
        return $this->Switch;
    }

    /**
     * Generated from protobuf field <code>bool Switch = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setSwitch($var)
    {
        GPBUtil::checkBool($var);
        $this->Switch = $var;

        return $this;
    }

}

