<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.IpControl</code>
 */
class IpControl extends \Google\Protobuf\Internal\Message
{
    /**
     * ip列表类型
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.BWListType IpType = 1;</code>
     */
    protected $IpType = 0;
    /**
     * ip列表
     *
     * Generated from protobuf field <code>repeated string Ips = 2;</code>
     */
    private $Ips;
    /**
     * ip列表开启状态
     *
     * Generated from protobuf field <code>string Status = 3;</code>
     */
    protected $Status = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $IpType
     *           ip列表类型
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Ips
     *           ip列表
     *     @type string $Status
     *           ip列表开启状态
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * ip列表类型
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.BWListType IpType = 1;</code>
     * @return int
     */
    public function getIpType()
    {
        return $this->IpType;
    }

    /**
     * ip列表类型
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.BWListType IpType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setIpType($var)
    {
        GPBUtil::checkEnum($var, \Byteplus\Service\Vod\Models\Business\BWListType::class);
        $this->IpType = $var;

        return $this;
    }

    /**
     * ip列表
     *
     * Generated from protobuf field <code>repeated string Ips = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIps()
    {
        return $this->Ips;
    }

    /**
     * ip列表
     *
     * Generated from protobuf field <code>repeated string Ips = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Ips = $arr;

        return $this;
    }

    /**
     * ip列表开启状态
     *
     * Generated from protobuf field <code>string Status = 3;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     * ip列表开启状态
     *
     * Generated from protobuf field <code>string Status = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->Status = $var;

        return $this;
    }

}

