<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.MethodDeniedRuleControl</code>
 */
class MethodDeniedRuleControl extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.MethodDeniedRule MethodDeniedRule = 1;</code>
     */
    protected $MethodDeniedRule = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\MethodDeniedRule $MethodDeniedRule
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.MethodDeniedRule MethodDeniedRule = 1;</code>
     * @return \Byteplus\Service\Vod\Models\Business\MethodDeniedRule|null
     */
    public function getMethodDeniedRule()
    {
        return $this->MethodDeniedRule;
    }

    public function hasMethodDeniedRule()
    {
        return isset($this->MethodDeniedRule);
    }

    public function clearMethodDeniedRule()
    {
        unset($this->MethodDeniedRule);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.MethodDeniedRule MethodDeniedRule = 1;</code>
     * @param \Byteplus\Service\Vod\Models\Business\MethodDeniedRule $var
     * @return $this
     */
    public function setMethodDeniedRule($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\MethodDeniedRule::class);
        $this->MethodDeniedRule = $var;

        return $this;
    }

}

