<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_common.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.MirrorSrcRule</code>
 */
class MirrorSrcRule extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue Id = 1;</code>
     */
    protected $Id = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue Enabled = 2;</code>
     */
    protected $Enabled = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodMirrorSrcOriginType OriginType = 3;</code>
     */
    protected $OriginType = 0;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.MirrorSrcCondition Condition = 4;</code>
     */
    protected $Condition = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.PublicSourceConf PublicSource = 5;</code>
     */
    protected $PublicSource = null;
    /**
     * Generated from protobuf field <code>int64 CreatedAt = 6;</code>
     */
    protected $CreatedAt = 0;
    /**
     * Generated from protobuf field <code>int64 UpdatedAt = 7;</code>
     */
    protected $UpdatedAt = 0;
    /**
     * Generated from protobuf field <code>int64 DeletedAt = 8;</code>
     */
    protected $DeletedAt = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\StringValue $Id
     *     @type \Google\Protobuf\BoolValue $Enabled
     *     @type int $OriginType
     *     @type \Byteplus\Service\Vod\Models\Business\MirrorSrcCondition $Condition
     *     @type \Byteplus\Service\Vod\Models\Business\PublicSourceConf $PublicSource
     *     @type int|string $CreatedAt
     *     @type int|string $UpdatedAt
     *     @type int|string $DeletedAt
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue Id = 1;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getId()
    {
        return $this->Id;
    }

    public function hasId()
    {
        return isset($this->Id);
    }

    public function clearId()
    {
        unset($this->Id);
    }

    /**
     * Returns the unboxed value from <code>getId()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue Id = 1;</code>
     * @return string|null
     */
    public function getIdUnwrapped()
    {
        return $this->readWrapperValue("Id");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue Id = 1;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->Id = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue Id = 1;</code>
     * @param string|null $var
     * @return $this
     */
    public function setIdUnwrapped($var)
    {
        $this->writeWrapperValue("Id", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue Enabled = 2;</code>
     * @return \Google\Protobuf\BoolValue|null
     */
    public function getEnabled()
    {
        return $this->Enabled;
    }

    public function hasEnabled()
    {
        return isset($this->Enabled);
    }

    public function clearEnabled()
    {
        unset($this->Enabled);
    }

    /**
     * Returns the unboxed value from <code>getEnabled()</code>

     * Generated from protobuf field <code>.google.protobuf.BoolValue Enabled = 2;</code>
     * @return bool|null
     */
    public function getEnabledUnwrapped()
    {
        return $this->readWrapperValue("Enabled");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue Enabled = 2;</code>
     * @param \Google\Protobuf\BoolValue $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\BoolValue::class);
        $this->Enabled = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BoolValue object.

     * Generated from protobuf field <code>.google.protobuf.BoolValue Enabled = 2;</code>
     * @param bool|null $var
     * @return $this
     */
    public function setEnabledUnwrapped($var)
    {
        $this->writeWrapperValue("Enabled", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodMirrorSrcOriginType OriginType = 3;</code>
     * @return int
     */
    public function getOriginType()
    {
        return $this->OriginType;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodMirrorSrcOriginType OriginType = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOriginType($var)
    {
        GPBUtil::checkEnum($var, \Byteplus\Service\Vod\Models\Business\VodMirrorSrcOriginType::class);
        $this->OriginType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.MirrorSrcCondition Condition = 4;</code>
     * @return \Byteplus\Service\Vod\Models\Business\MirrorSrcCondition|null
     */
    public function getCondition()
    {
        return $this->Condition;
    }

    public function hasCondition()
    {
        return isset($this->Condition);
    }

    public function clearCondition()
    {
        unset($this->Condition);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.MirrorSrcCondition Condition = 4;</code>
     * @param \Byteplus\Service\Vod\Models\Business\MirrorSrcCondition $var
     * @return $this
     */
    public function setCondition($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\MirrorSrcCondition::class);
        $this->Condition = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.PublicSourceConf PublicSource = 5;</code>
     * @return \Byteplus\Service\Vod\Models\Business\PublicSourceConf|null
     */
    public function getPublicSource()
    {
        return $this->PublicSource;
    }

    public function hasPublicSource()
    {
        return isset($this->PublicSource);
    }

    public function clearPublicSource()
    {
        unset($this->PublicSource);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.PublicSourceConf PublicSource = 5;</code>
     * @param \Byteplus\Service\Vod\Models\Business\PublicSourceConf $var
     * @return $this
     */
    public function setPublicSource($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\PublicSourceConf::class);
        $this->PublicSource = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 CreatedAt = 6;</code>
     * @return int|string
     */
    public function getCreatedAt()
    {
        return $this->CreatedAt;
    }

    /**
     * Generated from protobuf field <code>int64 CreatedAt = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->CreatedAt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 UpdatedAt = 7;</code>
     * @return int|string
     */
    public function getUpdatedAt()
    {
        return $this->UpdatedAt;
    }

    /**
     * Generated from protobuf field <code>int64 UpdatedAt = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->UpdatedAt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 DeletedAt = 8;</code>
     * @return int|string
     */
    public function getDeletedAt()
    {
        return $this->DeletedAt;
    }

    /**
     * Generated from protobuf field <code>int64 DeletedAt = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeletedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->DeletedAt = $var;

        return $this;
    }

}

