<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_common.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.MirrorSrcCondition</code>
 */
class MirrorSrcCondition extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated int64 HttpCode = 1;</code>
     */
    private $HttpCode;
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue KeyPrefix = 2;</code>
     */
    protected $KeyPrefix = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue KeySuffix = 3;</code>
     */
    protected $KeySuffix = null;
    /**
     * Generated from protobuf field <code>repeated string AllowHost = 4;</code>
     */
    private $AllowHost;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $HttpCode
     *     @type \Google\Protobuf\StringValue $KeyPrefix
     *     @type \Google\Protobuf\StringValue $KeySuffix
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $AllowHost
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated int64 HttpCode = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHttpCode()
    {
        return $this->HttpCode;
    }

    /**
     * Generated from protobuf field <code>repeated int64 HttpCode = 1;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHttpCode($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->HttpCode = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue KeyPrefix = 2;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getKeyPrefix()
    {
        return $this->KeyPrefix;
    }

    public function hasKeyPrefix()
    {
        return isset($this->KeyPrefix);
    }

    public function clearKeyPrefix()
    {
        unset($this->KeyPrefix);
    }

    /**
     * Returns the unboxed value from <code>getKeyPrefix()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue KeyPrefix = 2;</code>
     * @return string|null
     */
    public function getKeyPrefixUnwrapped()
    {
        return $this->readWrapperValue("KeyPrefix");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue KeyPrefix = 2;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setKeyPrefix($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->KeyPrefix = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue KeyPrefix = 2;</code>
     * @param string|null $var
     * @return $this
     */
    public function setKeyPrefixUnwrapped($var)
    {
        $this->writeWrapperValue("KeyPrefix", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue KeySuffix = 3;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getKeySuffix()
    {
        return $this->KeySuffix;
    }

    public function hasKeySuffix()
    {
        return isset($this->KeySuffix);
    }

    public function clearKeySuffix()
    {
        unset($this->KeySuffix);
    }

    /**
     * Returns the unboxed value from <code>getKeySuffix()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue KeySuffix = 3;</code>
     * @return string|null
     */
    public function getKeySuffixUnwrapped()
    {
        return $this->readWrapperValue("KeySuffix");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue KeySuffix = 3;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setKeySuffix($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->KeySuffix = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue KeySuffix = 3;</code>
     * @param string|null $var
     * @return $this
     */
    public function setKeySuffixUnwrapped($var)
    {
        $this->writeWrapperValue("KeySuffix", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>repeated string AllowHost = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAllowHost()
    {
        return $this->AllowHost;
    }

    /**
     * Generated from protobuf field <code>repeated string AllowHost = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAllowHost($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->AllowHost = $arr;

        return $this;
    }

}

