<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.OriginArgControl</code>
 */
class OriginArgControl extends \Google\Protobuf\Internal\Message
{
    /**
     *表示回源参数的设置。当前您仅能对 OriginArgComponents 中的 Action
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.OriginRule OriginArg = 1;</code>
     */
    private $OriginArg;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\OriginRule[]|\Google\Protobuf\Internal\RepeatedField $OriginArg
     *          表示回源参数的设置。当前您仅能对 OriginArgComponents 中的 Action
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     *表示回源参数的设置。当前您仅能对 OriginArgComponents 中的 Action
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.OriginRule OriginArg = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOriginArg()
    {
        return $this->OriginArg;
    }

    /**
     *表示回源参数的设置。当前您仅能对 OriginArgComponents 中的 Action
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.OriginRule OriginArg = 1;</code>
     * @param \Byteplus\Service\Vod\Models\Business\OriginRule[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOriginArg($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Byteplus\Service\Vod\Models\Business\OriginRule::class);
        $this->OriginArg = $arr;

        return $this;
    }

}

