<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.Origin</code>
 */
class Origin extends \Google\Protobuf\Internal\Message
{
    /**
     *源站类型
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.SourceStationType SourceStationType = 1;</code>
     */
    protected $SourceStationType = 0;
    /**
     *源站地址类型
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.SourceStationAddressType SourceStationAddressType = 2;</code>
     */
    protected $SourceStationAddressType = 0;
    /**
     *园站地址列表
     *
     * Generated from protobuf field <code>repeated string Origins = 3;</code>
     */
    private $Origins;
    /**
     *加速区域
     *
     * Generated from protobuf field <code>string Area = 4;</code>
     */
    protected $Area = '';
    /**
     *源站配置模块
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.CdnOriginRule Origin = 5;</code>
     */
    private $Origin;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $SourceStationType
     *          源站类型
     *     @type int $SourceStationAddressType
     *          源站地址类型
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Origins
     *          园站地址列表
     *     @type string $Area
     *          加速区域
     *     @type \Byteplus\Service\Vod\Models\Business\CdnOriginRule[]|\Google\Protobuf\Internal\RepeatedField $Origin
     *          源站配置模块
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     *源站类型
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.SourceStationType SourceStationType = 1;</code>
     * @return int
     */
    public function getSourceStationType()
    {
        return $this->SourceStationType;
    }

    /**
     *源站类型
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.SourceStationType SourceStationType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSourceStationType($var)
    {
        GPBUtil::checkEnum($var, \Byteplus\Service\Vod\Models\Business\SourceStationType::class);
        $this->SourceStationType = $var;

        return $this;
    }

    /**
     *源站地址类型
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.SourceStationAddressType SourceStationAddressType = 2;</code>
     * @return int
     */
    public function getSourceStationAddressType()
    {
        return $this->SourceStationAddressType;
    }

    /**
     *源站地址类型
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.SourceStationAddressType SourceStationAddressType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSourceStationAddressType($var)
    {
        GPBUtil::checkEnum($var, \Byteplus\Service\Vod\Models\Business\SourceStationAddressType::class);
        $this->SourceStationAddressType = $var;

        return $this;
    }

    /**
     *园站地址列表
     *
     * Generated from protobuf field <code>repeated string Origins = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrigins()
    {
        return $this->Origins;
    }

    /**
     *园站地址列表
     *
     * Generated from protobuf field <code>repeated string Origins = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrigins($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Origins = $arr;

        return $this;
    }

    /**
     *加速区域
     *
     * Generated from protobuf field <code>string Area = 4;</code>
     * @return string
     */
    public function getArea()
    {
        return $this->Area;
    }

    /**
     *加速区域
     *
     * Generated from protobuf field <code>string Area = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setArea($var)
    {
        GPBUtil::checkString($var, True);
        $this->Area = $var;

        return $this;
    }

    /**
     *源站配置模块
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.CdnOriginRule Origin = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrigin()
    {
        return $this->Origin;
    }

    /**
     *源站配置模块
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.CdnOriginRule Origin = 5;</code>
     * @param \Byteplus\Service\Vod\Models\Business\CdnOriginRule[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrigin($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Byteplus\Service\Vod\Models\Business\CdnOriginRule::class);
        $this->Origin = $arr;

        return $this;
    }

}

