<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.OriginSniControl</code>
 */
class OriginSniControl extends \Google\Protobuf\Internal\Message
{
    /**
     *表示此配置是否开启
     *
     * Generated from protobuf field <code>string Status = 1;</code>
     */
    protected $Status = '';
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.OriginSni OriginSni = 2;</code>
     */
    protected $OriginSni = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Status
     *          表示此配置是否开启
     *     @type \Byteplus\Service\Vod\Models\Business\OriginSni $OriginSni
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     *表示此配置是否开启
     *
     * Generated from protobuf field <code>string Status = 1;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     *表示此配置是否开启
     *
     * Generated from protobuf field <code>string Status = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->Status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.OriginSni OriginSni = 2;</code>
     * @return \Byteplus\Service\Vod\Models\Business\OriginSni|null
     */
    public function getOriginSni()
    {
        return $this->OriginSni;
    }

    public function hasOriginSni()
    {
        return isset($this->OriginSni);
    }

    public function clearOriginSni()
    {
        unset($this->OriginSni);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.OriginSni OriginSni = 2;</code>
     * @param \Byteplus\Service\Vod\Models\Business\OriginSni $var
     * @return $this
     */
    public function setOriginSni($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\OriginSni::class);
        $this->OriginSni = $var;

        return $this;
    }

}

