<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_workflow.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.OverrideParams</code>
 */
class OverrideParams extends \Google\Protobuf\Internal\Message
{
    /**
     * 水印覆盖参数
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.LogoOverride Logo = 1;</code>
     */
    private $Logo;
    /**
     * 视频转码覆盖参数
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.TranscodeVideoOverride TranscodeVideo = 2;</code>
     */
    private $TranscodeVideo;
    /**
     * 音频转码覆盖参数
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.TranscodeAudioOverride TranscodeAudio = 3;</code>
     */
    private $TranscodeAudio;
    /**
     * 截图覆盖参数
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.SnapshotOverride Snapshot = 4;</code>
     */
    private $Snapshot;
    /**
     * 增强覆盖参数
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.EnhanceOverride Enhance = 5;</code>
     */
    protected $Enhance = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\LogoOverride[]|\Google\Protobuf\Internal\RepeatedField $Logo
     *           水印覆盖参数
     *     @type \Byteplus\Service\Vod\Models\Business\TranscodeVideoOverride[]|\Google\Protobuf\Internal\RepeatedField $TranscodeVideo
     *           视频转码覆盖参数
     *     @type \Byteplus\Service\Vod\Models\Business\TranscodeAudioOverride[]|\Google\Protobuf\Internal\RepeatedField $TranscodeAudio
     *           音频转码覆盖参数
     *     @type \Byteplus\Service\Vod\Models\Business\SnapshotOverride[]|\Google\Protobuf\Internal\RepeatedField $Snapshot
     *           截图覆盖参数
     *     @type \Byteplus\Service\Vod\Models\Business\EnhanceOverride $Enhance
     *           增强覆盖参数
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodWorkflow::initOnce();
        parent::__construct($data);
    }

    /**
     * 水印覆盖参数
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.LogoOverride Logo = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLogo()
    {
        return $this->Logo;
    }

    /**
     * 水印覆盖参数
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.LogoOverride Logo = 1;</code>
     * @param \Byteplus\Service\Vod\Models\Business\LogoOverride[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLogo($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Byteplus\Service\Vod\Models\Business\LogoOverride::class);
        $this->Logo = $arr;

        return $this;
    }

    /**
     * 视频转码覆盖参数
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.TranscodeVideoOverride TranscodeVideo = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTranscodeVideo()
    {
        return $this->TranscodeVideo;
    }

    /**
     * 视频转码覆盖参数
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.TranscodeVideoOverride TranscodeVideo = 2;</code>
     * @param \Byteplus\Service\Vod\Models\Business\TranscodeVideoOverride[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTranscodeVideo($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Byteplus\Service\Vod\Models\Business\TranscodeVideoOverride::class);
        $this->TranscodeVideo = $arr;

        return $this;
    }

    /**
     * 音频转码覆盖参数
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.TranscodeAudioOverride TranscodeAudio = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTranscodeAudio()
    {
        return $this->TranscodeAudio;
    }

    /**
     * 音频转码覆盖参数
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.TranscodeAudioOverride TranscodeAudio = 3;</code>
     * @param \Byteplus\Service\Vod\Models\Business\TranscodeAudioOverride[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTranscodeAudio($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Byteplus\Service\Vod\Models\Business\TranscodeAudioOverride::class);
        $this->TranscodeAudio = $arr;

        return $this;
    }

    /**
     * 截图覆盖参数
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.SnapshotOverride Snapshot = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSnapshot()
    {
        return $this->Snapshot;
    }

    /**
     * 截图覆盖参数
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.SnapshotOverride Snapshot = 4;</code>
     * @param \Byteplus\Service\Vod\Models\Business\SnapshotOverride[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSnapshot($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Byteplus\Service\Vod\Models\Business\SnapshotOverride::class);
        $this->Snapshot = $arr;

        return $this;
    }

    /**
     * 增强覆盖参数
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.EnhanceOverride Enhance = 5;</code>
     * @return \Byteplus\Service\Vod\Models\Business\EnhanceOverride|null
     */
    public function getEnhance()
    {
        return $this->Enhance;
    }

    public function hasEnhance()
    {
        return isset($this->Enhance);
    }

    public function clearEnhance()
    {
        unset($this->Enhance);
    }

    /**
     * 增强覆盖参数
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.EnhanceOverride Enhance = 5;</code>
     * @param \Byteplus\Service\Vod\Models\Business\EnhanceOverride $var
     * @return $this
     */
    public function setEnhance($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\EnhanceOverride::class);
        $this->Enhance = $var;

        return $this;
    }

}

