<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_common.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.PublicSourceConf</code>
 */
class PublicSourceConf extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.MirrorSrcS3Conf S3 = 1;</code>
     */
    protected $S3 = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\MirrorSrcS3Conf $S3
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.MirrorSrcS3Conf S3 = 1;</code>
     * @return \Byteplus\Service\Vod\Models\Business\MirrorSrcS3Conf|null
     */
    public function getS3()
    {
        return $this->S3;
    }

    public function hasS3()
    {
        return isset($this->S3);
    }

    public function clearS3()
    {
        unset($this->S3);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.MirrorSrcS3Conf S3 = 1;</code>
     * @param \Byteplus\Service\Vod\Models\Business\MirrorSrcS3Conf $var
     * @return $this
     */
    public function setS3($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\MirrorSrcS3Conf::class);
        $this->S3 = $var;

        return $this;
    }

}

