<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.RemoteAuth</code>
 */
class RemoteAuth extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool Switch = 1;</code>
     */
    protected $Switch = false;
    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.RemoteAuthRule RemoteAuthRules = 2;</code>
     */
    private $RemoteAuthRules;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $Switch
     *     @type \Byteplus\Service\Vod\Models\Business\RemoteAuthRule[]|\Google\Protobuf\Internal\RepeatedField $RemoteAuthRules
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool Switch = 1;</code>
     * @return bool
     */
    public function getSwitch()
    {
        return $this->Switch;
    }

    /**
     * Generated from protobuf field <code>bool Switch = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSwitch($var)
    {
        GPBUtil::checkBool($var);
        $this->Switch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.RemoteAuthRule RemoteAuthRules = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRemoteAuthRules()
    {
        return $this->RemoteAuthRules;
    }

    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.RemoteAuthRule RemoteAuthRules = 2;</code>
     * @param \Byteplus\Service\Vod\Models\Business\RemoteAuthRule[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRemoteAuthRules($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Byteplus\Service\Vod\Models\Business\RemoteAuthRule::class);
        $this->RemoteAuthRules = $arr;

        return $this;
    }

}

