<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.RemoteAuthRuleAction</code>
 */
class RemoteAuthRuleAction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.AuthModeConfig AuthModeConfig = 1;</code>
     */
    protected $AuthModeConfig = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.AuthResponseConfig AuthResponseConfig = 2;</code>
     */
    protected $AuthResponseConfig = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.QueryStringRules QueryStringRules = 3;</code>
     */
    protected $QueryStringRules = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.AuthRequestHeaderRule RequestHeaderRules = 4;</code>
     */
    protected $RequestHeaderRules = null;
    /**
     * Generated from protobuf field <code>string RequestBodyRules = 5;</code>
     */
    protected $RequestBodyRules = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\AuthModeConfig $AuthModeConfig
     *     @type \Byteplus\Service\Vod\Models\Business\AuthResponseConfig $AuthResponseConfig
     *     @type \Byteplus\Service\Vod\Models\Business\QueryStringRules $QueryStringRules
     *     @type \Byteplus\Service\Vod\Models\Business\AuthRequestHeaderRule $RequestHeaderRules
     *     @type string $RequestBodyRules
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.AuthModeConfig AuthModeConfig = 1;</code>
     * @return \Byteplus\Service\Vod\Models\Business\AuthModeConfig|null
     */
    public function getAuthModeConfig()
    {
        return $this->AuthModeConfig;
    }

    public function hasAuthModeConfig()
    {
        return isset($this->AuthModeConfig);
    }

    public function clearAuthModeConfig()
    {
        unset($this->AuthModeConfig);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.AuthModeConfig AuthModeConfig = 1;</code>
     * @param \Byteplus\Service\Vod\Models\Business\AuthModeConfig $var
     * @return $this
     */
    public function setAuthModeConfig($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\AuthModeConfig::class);
        $this->AuthModeConfig = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.AuthResponseConfig AuthResponseConfig = 2;</code>
     * @return \Byteplus\Service\Vod\Models\Business\AuthResponseConfig|null
     */
    public function getAuthResponseConfig()
    {
        return $this->AuthResponseConfig;
    }

    public function hasAuthResponseConfig()
    {
        return isset($this->AuthResponseConfig);
    }

    public function clearAuthResponseConfig()
    {
        unset($this->AuthResponseConfig);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.AuthResponseConfig AuthResponseConfig = 2;</code>
     * @param \Byteplus\Service\Vod\Models\Business\AuthResponseConfig $var
     * @return $this
     */
    public function setAuthResponseConfig($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\AuthResponseConfig::class);
        $this->AuthResponseConfig = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.QueryStringRules QueryStringRules = 3;</code>
     * @return \Byteplus\Service\Vod\Models\Business\QueryStringRules|null
     */
    public function getQueryStringRules()
    {
        return $this->QueryStringRules;
    }

    public function hasQueryStringRules()
    {
        return isset($this->QueryStringRules);
    }

    public function clearQueryStringRules()
    {
        unset($this->QueryStringRules);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.QueryStringRules QueryStringRules = 3;</code>
     * @param \Byteplus\Service\Vod\Models\Business\QueryStringRules $var
     * @return $this
     */
    public function setQueryStringRules($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\QueryStringRules::class);
        $this->QueryStringRules = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.AuthRequestHeaderRule RequestHeaderRules = 4;</code>
     * @return \Byteplus\Service\Vod\Models\Business\AuthRequestHeaderRule|null
     */
    public function getRequestHeaderRules()
    {
        return $this->RequestHeaderRules;
    }

    public function hasRequestHeaderRules()
    {
        return isset($this->RequestHeaderRules);
    }

    public function clearRequestHeaderRules()
    {
        unset($this->RequestHeaderRules);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.AuthRequestHeaderRule RequestHeaderRules = 4;</code>
     * @param \Byteplus\Service\Vod\Models\Business\AuthRequestHeaderRule $var
     * @return $this
     */
    public function setRequestHeaderRules($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\AuthRequestHeaderRule::class);
        $this->RequestHeaderRules = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string RequestBodyRules = 5;</code>
     * @return string
     */
    public function getRequestBodyRules()
    {
        return $this->RequestBodyRules;
    }

    /**
     * Generated from protobuf field <code>string RequestBodyRules = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestBodyRules($var)
    {
        GPBUtil::checkString($var, True);
        $this->RequestBodyRules = $var;

        return $this;
    }

}

