<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.RequestHeaderRule</code>
 */
class RequestHeaderRule extends \Google\Protobuf\Internal\Message
{
    /**
     *请求头配置暂时不支持条件配置。您无需指定该参数。您也可以设置该参数为
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.Condition Condition = 1;</code>
     */
    protected $Condition = null;
    /**
     * null
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.RequestHeaderAction RequestHeaderAction = 2;</code>
     */
    protected $RequestHeaderAction = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\Condition $Condition
     *          请求头配置暂时不支持条件配置。您无需指定该参数。您也可以设置该参数为
     *     @type \Byteplus\Service\Vod\Models\Business\RequestHeaderAction $RequestHeaderAction
     *           null
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     *请求头配置暂时不支持条件配置。您无需指定该参数。您也可以设置该参数为
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.Condition Condition = 1;</code>
     * @return \Byteplus\Service\Vod\Models\Business\Condition|null
     */
    public function getCondition()
    {
        return $this->Condition;
    }

    public function hasCondition()
    {
        return isset($this->Condition);
    }

    public function clearCondition()
    {
        unset($this->Condition);
    }

    /**
     *请求头配置暂时不支持条件配置。您无需指定该参数。您也可以设置该参数为
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.Condition Condition = 1;</code>
     * @param \Byteplus\Service\Vod\Models\Business\Condition $var
     * @return $this
     */
    public function setCondition($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\Condition::class);
        $this->Condition = $var;

        return $this;
    }

    /**
     * null
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.RequestHeaderAction RequestHeaderAction = 2;</code>
     * @return \Byteplus\Service\Vod\Models\Business\RequestHeaderAction|null
     */
    public function getRequestHeaderAction()
    {
        return $this->RequestHeaderAction;
    }

    public function hasRequestHeaderAction()
    {
        return isset($this->RequestHeaderAction);
    }

    public function clearRequestHeaderAction()
    {
        unset($this->RequestHeaderAction);
    }

    /**
     * null
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.RequestHeaderAction RequestHeaderAction = 2;</code>
     * @param \Byteplus\Service\Vod\Models\Business\RequestHeaderAction $var
     * @return $this
     */
    public function setRequestHeaderAction($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\RequestHeaderAction::class);
        $this->RequestHeaderAction = $var;

        return $this;
    }

}

