<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.RewriteM3u8Rule</code>
 */
class RewriteM3u8Rule extends \Google\Protobuf\Internal\Message
{
    /**
     * 删除分片URL原参数
     *
     * Generated from protobuf field <code>bool DeleteParam = 1;</code>
     */
    protected $DeleteParam = false;
    /**
     * 继承M3U8非签名参数
     *
     * Generated from protobuf field <code>bool KeepM3u8Param = 2;</code>
     */
    protected $KeepM3u8Param = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $DeleteParam
     *           删除分片URL原参数
     *     @type bool $KeepM3u8Param
     *           继承M3U8非签名参数
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * 删除分片URL原参数
     *
     * Generated from protobuf field <code>bool DeleteParam = 1;</code>
     * @return bool
     */
    public function getDeleteParam()
    {
        return $this->DeleteParam;
    }

    /**
     * 删除分片URL原参数
     *
     * Generated from protobuf field <code>bool DeleteParam = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setDeleteParam($var)
    {
        GPBUtil::checkBool($var);
        $this->DeleteParam = $var;

        return $this;
    }

    /**
     * 继承M3U8非签名参数
     *
     * Generated from protobuf field <code>bool KeepM3u8Param = 2;</code>
     * @return bool
     */
    public function getKeepM3U8Param()
    {
        return $this->KeepM3u8Param;
    }

    /**
     * 继承M3U8非签名参数
     *
     * Generated from protobuf field <code>bool KeepM3u8Param = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setKeepM3U8Param($var)
    {
        GPBUtil::checkBool($var);
        $this->KeepM3u8Param = $var;

        return $this;
    }

}

