<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.RewriteHLS</code>
 */
class RewriteHLS extends \Google\Protobuf\Internal\Message
{
    /**
     * 是否开启标准HLS加密改写
     *
     * Generated from protobuf field <code>bool Switch = 1;</code>
     */
    protected $Switch = false;
    /**
     * 加密参数名称
     *
     * Generated from protobuf field <code>string SignName = 2;</code>
     */
    protected $SignName = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $Switch
     *           是否开启标准HLS加密改写
     *     @type string $SignName
     *           加密参数名称
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * 是否开启标准HLS加密改写
     *
     * Generated from protobuf field <code>bool Switch = 1;</code>
     * @return bool
     */
    public function getSwitch()
    {
        return $this->Switch;
    }

    /**
     * 是否开启标准HLS加密改写
     *
     * Generated from protobuf field <code>bool Switch = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSwitch($var)
    {
        GPBUtil::checkBool($var);
        $this->Switch = $var;

        return $this;
    }

    /**
     * 加密参数名称
     *
     * Generated from protobuf field <code>string SignName = 2;</code>
     * @return string
     */
    public function getSignName()
    {
        return $this->SignName;
    }

    /**
     * 加密参数名称
     *
     * Generated from protobuf field <code>string SignName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSignName($var)
    {
        GPBUtil::checkString($var, True);
        $this->SignName = $var;

        return $this;
    }

}

