<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.SignedUrlAuthControl</code>
 */
class SignedUrlAuthControl extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.SignedUrlAuth SignedUrlAuth = 1;</code>
     */
    protected $SignedUrlAuth = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\SignedUrlAuth $SignedUrlAuth
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.SignedUrlAuth SignedUrlAuth = 1;</code>
     * @return \Byteplus\Service\Vod\Models\Business\SignedUrlAuth|null
     */
    public function getSignedUrlAuth()
    {
        return $this->SignedUrlAuth;
    }

    public function hasSignedUrlAuth()
    {
        return isset($this->SignedUrlAuth);
    }

    public function clearSignedUrlAuth()
    {
        unset($this->SignedUrlAuth);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.SignedUrlAuth SignedUrlAuth = 1;</code>
     * @param \Byteplus\Service\Vod\Models\Business\SignedUrlAuth $var
     * @return $this
     */
    public function setSignedUrlAuth($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\SignedUrlAuth::class);
        $this->SignedUrlAuth = $var;

        return $this;
    }

}

