<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.SignedUrlAuthAction</code>
 */
class SignedUrlAuthAction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string URLAuthType = 1;</code>
     */
    protected $URLAuthType = '';
    /**
     * Generated from protobuf field <code>string MasterSecretKey = 2;</code>
     */
    protected $MasterSecretKey = '';
    /**
     * Generated from protobuf field <code>string BackupSecretKey = 3;</code>
     */
    protected $BackupSecretKey = '';
    /**
     * Generated from protobuf field <code>string SignName = 4;</code>
     */
    protected $SignName = '';
    /**
     * Generated from protobuf field <code>string TimeName = 5;</code>
     */
    protected $TimeName = '';
    /**
     * Generated from protobuf field <code>double Duration = 6;</code>
     */
    protected $Duration = 0.0;
    /**
     * Generated from protobuf field <code>string TimeFormat = 7;</code>
     */
    protected $TimeFormat = '';
    /**
     * Generated from protobuf field <code>bool RewriteM3u8 = 8;</code>
     */
    protected $RewriteM3u8 = false;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.CustomVariableRules CustomVariableRules = 9;</code>
     */
    protected $CustomVariableRules = null;
    /**
     * Generated from protobuf field <code>repeated string SignatureRule = 10;</code>
     */
    private $SignatureRule;
    /**
     * "M3U8 改写" 功能的配置
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.RewriteM3u8Rule RewriteM3u8Rule = 11;</code>
     */
    protected $RewriteM3u8Rule = null;
    /**
     * Generated from protobuf field <code>repeated string RewritedM3u8Tags = 12;</code>
     */
    private $RewritedM3u8Tags;
    /**
     * Generated from protobuf field <code>bool EnableM3u8TagRewrite = 13;</code>
     */
    protected $EnableM3u8TagRewrite = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $URLAuthType
     *     @type string $MasterSecretKey
     *     @type string $BackupSecretKey
     *     @type string $SignName
     *     @type string $TimeName
     *     @type float $Duration
     *     @type string $TimeFormat
     *     @type bool $RewriteM3u8
     *     @type \Byteplus\Service\Vod\Models\Business\CustomVariableRules $CustomVariableRules
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $SignatureRule
     *     @type \Byteplus\Service\Vod\Models\Business\RewriteM3u8Rule $RewriteM3u8Rule
     *           "M3U8 改写" 功能的配置
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $RewritedM3u8Tags
     *     @type bool $EnableM3u8TagRewrite
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string URLAuthType = 1;</code>
     * @return string
     */
    public function getURLAuthType()
    {
        return $this->URLAuthType;
    }

    /**
     * Generated from protobuf field <code>string URLAuthType = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setURLAuthType($var)
    {
        GPBUtil::checkString($var, True);
        $this->URLAuthType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string MasterSecretKey = 2;</code>
     * @return string
     */
    public function getMasterSecretKey()
    {
        return $this->MasterSecretKey;
    }

    /**
     * Generated from protobuf field <code>string MasterSecretKey = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMasterSecretKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->MasterSecretKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string BackupSecretKey = 3;</code>
     * @return string
     */
    public function getBackupSecretKey()
    {
        return $this->BackupSecretKey;
    }

    /**
     * Generated from protobuf field <code>string BackupSecretKey = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBackupSecretKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->BackupSecretKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string SignName = 4;</code>
     * @return string
     */
    public function getSignName()
    {
        return $this->SignName;
    }

    /**
     * Generated from protobuf field <code>string SignName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSignName($var)
    {
        GPBUtil::checkString($var, True);
        $this->SignName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string TimeName = 5;</code>
     * @return string
     */
    public function getTimeName()
    {
        return $this->TimeName;
    }

    /**
     * Generated from protobuf field <code>string TimeName = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeName($var)
    {
        GPBUtil::checkString($var, True);
        $this->TimeName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double Duration = 6;</code>
     * @return float
     */
    public function getDuration()
    {
        return $this->Duration;
    }

    /**
     * Generated from protobuf field <code>double Duration = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setDuration($var)
    {
        GPBUtil::checkDouble($var);
        $this->Duration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string TimeFormat = 7;</code>
     * @return string
     */
    public function getTimeFormat()
    {
        return $this->TimeFormat;
    }

    /**
     * Generated from protobuf field <code>string TimeFormat = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeFormat($var)
    {
        GPBUtil::checkString($var, True);
        $this->TimeFormat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool RewriteM3u8 = 8;</code>
     * @return bool
     */
    public function getRewriteM3U8()
    {
        return $this->RewriteM3u8;
    }

    /**
     * Generated from protobuf field <code>bool RewriteM3u8 = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setRewriteM3U8($var)
    {
        GPBUtil::checkBool($var);
        $this->RewriteM3u8 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.CustomVariableRules CustomVariableRules = 9;</code>
     * @return \Byteplus\Service\Vod\Models\Business\CustomVariableRules|null
     */
    public function getCustomVariableRules()
    {
        return $this->CustomVariableRules;
    }

    public function hasCustomVariableRules()
    {
        return isset($this->CustomVariableRules);
    }

    public function clearCustomVariableRules()
    {
        unset($this->CustomVariableRules);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.CustomVariableRules CustomVariableRules = 9;</code>
     * @param \Byteplus\Service\Vod\Models\Business\CustomVariableRules $var
     * @return $this
     */
    public function setCustomVariableRules($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\CustomVariableRules::class);
        $this->CustomVariableRules = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string SignatureRule = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSignatureRule()
    {
        return $this->SignatureRule;
    }

    /**
     * Generated from protobuf field <code>repeated string SignatureRule = 10;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSignatureRule($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->SignatureRule = $arr;

        return $this;
    }

    /**
     * "M3U8 改写" 功能的配置
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.RewriteM3u8Rule RewriteM3u8Rule = 11;</code>
     * @return \Byteplus\Service\Vod\Models\Business\RewriteM3u8Rule|null
     */
    public function getRewriteM3U8Rule()
    {
        return $this->RewriteM3u8Rule;
    }

    public function hasRewriteM3U8Rule()
    {
        return isset($this->RewriteM3u8Rule);
    }

    public function clearRewriteM3U8Rule()
    {
        unset($this->RewriteM3u8Rule);
    }

    /**
     * "M3U8 改写" 功能的配置
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.RewriteM3u8Rule RewriteM3u8Rule = 11;</code>
     * @param \Byteplus\Service\Vod\Models\Business\RewriteM3u8Rule $var
     * @return $this
     */
    public function setRewriteM3U8Rule($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\RewriteM3u8Rule::class);
        $this->RewriteM3u8Rule = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string RewritedM3u8Tags = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRewritedM3U8Tags()
    {
        return $this->RewritedM3u8Tags;
    }

    /**
     * Generated from protobuf field <code>repeated string RewritedM3u8Tags = 12;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRewritedM3U8Tags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->RewritedM3u8Tags = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool EnableM3u8TagRewrite = 13;</code>
     * @return bool
     */
    public function getEnableM3U8TagRewrite()
    {
        return $this->EnableM3u8TagRewrite;
    }

    /**
     * Generated from protobuf field <code>bool EnableM3u8TagRewrite = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableM3U8TagRewrite($var)
    {
        GPBUtil::checkBool($var);
        $this->EnableM3u8TagRewrite = $var;

        return $this;
    }

}

