<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use UnexpectedValueException;

/**
 * 源站类型
 *
 * Protobuf type <code>Byteplus.Vod.Models.Business.SourceStationType</code>
 */
class SourceStationType
{
    /**
     * 未定义的源站类型
     *
     * Generated from protobuf enum <code>UndefinedSourceStationType = 0;</code>
     */
    const UndefinedSourceStationType = 0;
    /**
     * 点播源站
     *
     * Generated from protobuf enum <code>VodSourceStationType = 1;</code>
     */
    const VodSourceStationType = 1;
    /**
     * 第三方源站
     *
     * Generated from protobuf enum <code>ThirdPartySourceStationType = 2;</code>
     */
    const ThirdPartySourceStationType = 2;

    private static $valueToName = [
        self::UndefinedSourceStationType => 'UndefinedSourceStationType',
        self::VodSourceStationType => 'VodSourceStationType',
        self::ThirdPartySourceStationType => 'ThirdPartySourceStationType',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

