<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.SpeedLimitTime</code>
 */
class SpeedLimitTime extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string DayWeek = 1;</code>
     */
    protected $DayWeek = '';
    /**
     * Generated from protobuf field <code>string BeginTime = 2;</code>
     */
    protected $BeginTime = '';
    /**
     * Generated from protobuf field <code>string EndTime = 3;</code>
     */
    protected $EndTime = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $DayWeek
     *     @type string $BeginTime
     *     @type string $EndTime
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string DayWeek = 1;</code>
     * @return string
     */
    public function getDayWeek()
    {
        return $this->DayWeek;
    }

    /**
     * Generated from protobuf field <code>string DayWeek = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDayWeek($var)
    {
        GPBUtil::checkString($var, True);
        $this->DayWeek = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string BeginTime = 2;</code>
     * @return string
     */
    public function getBeginTime()
    {
        return $this->BeginTime;
    }

    /**
     * Generated from protobuf field <code>string BeginTime = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBeginTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->BeginTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string EndTime = 3;</code>
     * @return string
     */
    public function getEndTime()
    {
        return $this->EndTime;
    }

    /**
     * Generated from protobuf field <code>string EndTime = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->EndTime = $var;

        return $this;
    }

}

