<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.TimeoutRule</code>
 */
class TimeoutRule extends \Google\Protobuf\Internal\Message
{
    /**
     *表示超时时间的配置
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.TimeoutAction TimeoutAction = 1;</code>
     */
    protected $TimeoutAction = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\TimeoutAction $TimeoutAction
     *          表示超时时间的配置
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     *表示超时时间的配置
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.TimeoutAction TimeoutAction = 1;</code>
     * @return \Byteplus\Service\Vod\Models\Business\TimeoutAction|null
     */
    public function getTimeoutAction()
    {
        return $this->TimeoutAction;
    }

    public function hasTimeoutAction()
    {
        return isset($this->TimeoutAction);
    }

    public function clearTimeoutAction()
    {
        unset($this->TimeoutAction);
    }

    /**
     *表示超时时间的配置
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.TimeoutAction TimeoutAction = 1;</code>
     * @param \Byteplus\Service\Vod\Models\Business\TimeoutAction $var
     * @return $this
     */
    public function setTimeoutAction($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\TimeoutAction::class);
        $this->TimeoutAction = $var;

        return $this;
    }

}

