<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.TimeOutControl</code>
 */
class TimeOutControl extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Status = 1;</code>
     */
    protected $Status = '';
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.Timeout Timeout = 2;</code>
     */
    protected $Timeout = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Status
     *     @type \Byteplus\Service\Vod\Models\Business\Timeout $Timeout
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Status = 1;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     * Generated from protobuf field <code>string Status = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->Status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.Timeout Timeout = 2;</code>
     * @return \Byteplus\Service\Vod\Models\Business\Timeout|null
     */
    public function getTimeout()
    {
        return $this->Timeout;
    }

    public function hasTimeout()
    {
        return isset($this->Timeout);
    }

    public function clearTimeout()
    {
        unset($this->Timeout);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.Timeout Timeout = 2;</code>
     * @param \Byteplus\Service\Vod\Models\Business\Timeout $var
     * @return $this
     */
    public function setTimeout($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\Timeout::class);
        $this->Timeout = $var;

        return $this;
    }

}

