<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.Timeout</code>
 */
class Timeout extends \Google\Protobuf\Internal\Message
{
    /**
     *表示一组超时时间的配置。当前您只能指定一个配置。
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.TimeoutRule TimeoutRules = 1;</code>
     */
    private $TimeoutRules;
    /**
     *指定是否启用回源超时时间的配置。该参数有以下取值：
     *true：表示启用回源超时时间的配置。
     *false：表示禁用回源超时时间的配置。此时，TCP 请求和 HTTP
     *请求的超时时间使用系统默认值，分别是 2 秒和 60 秒。
     *
     * Generated from protobuf field <code>bool Switch = 2;</code>
     */
    protected $Switch = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\TimeoutRule[]|\Google\Protobuf\Internal\RepeatedField $TimeoutRules
     *          表示一组超时时间的配置。当前您只能指定一个配置。
     *     @type bool $Switch
     *          指定是否启用回源超时时间的配置。该参数有以下取值：
     *          true：表示启用回源超时时间的配置。
     *          false：表示禁用回源超时时间的配置。此时，TCP 请求和 HTTP
     *          请求的超时时间使用系统默认值，分别是 2 秒和 60 秒。
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     *表示一组超时时间的配置。当前您只能指定一个配置。
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.TimeoutRule TimeoutRules = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTimeoutRules()
    {
        return $this->TimeoutRules;
    }

    /**
     *表示一组超时时间的配置。当前您只能指定一个配置。
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.TimeoutRule TimeoutRules = 1;</code>
     * @param \Byteplus\Service\Vod\Models\Business\TimeoutRule[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTimeoutRules($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Byteplus\Service\Vod\Models\Business\TimeoutRule::class);
        $this->TimeoutRules = $arr;

        return $this;
    }

    /**
     *指定是否启用回源超时时间的配置。该参数有以下取值：
     *true：表示启用回源超时时间的配置。
     *false：表示禁用回源超时时间的配置。此时，TCP 请求和 HTTP
     *请求的超时时间使用系统默认值，分别是 2 秒和 60 秒。
     *
     * Generated from protobuf field <code>bool Switch = 2;</code>
     * @return bool
     */
    public function getSwitch()
    {
        return $this->Switch;
    }

    /**
     *指定是否启用回源超时时间的配置。该参数有以下取值：
     *true：表示启用回源超时时间的配置。
     *false：表示禁用回源超时时间的配置。此时，TCP 请求和 HTTP
     *请求的超时时间使用系统默认值，分别是 2 秒和 60 秒。
     *
     * Generated from protobuf field <code>bool Switch = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setSwitch($var)
    {
        GPBUtil::checkBool($var);
        $this->Switch = $var;

        return $this;
    }

}

