<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.UaAccessRuleControl</code>
 */
class UaAccessRuleControl extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.UserAgentAccessRule UserAgentAccessRule = 1;</code>
     */
    protected $UserAgentAccessRule = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\UserAgentAccessRule $UserAgentAccessRule
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.UserAgentAccessRule UserAgentAccessRule = 1;</code>
     * @return \Byteplus\Service\Vod\Models\Business\UserAgentAccessRule|null
     */
    public function getUserAgentAccessRule()
    {
        return $this->UserAgentAccessRule;
    }

    public function hasUserAgentAccessRule()
    {
        return isset($this->UserAgentAccessRule);
    }

    public function clearUserAgentAccessRule()
    {
        unset($this->UserAgentAccessRule);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.UserAgentAccessRule UserAgentAccessRule = 1;</code>
     * @param \Byteplus\Service\Vod\Models\Business\UserAgentAccessRule $var
     * @return $this
     */
    public function setUserAgentAccessRule($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\UserAgentAccessRule::class);
        $this->UserAgentAccessRule = $var;

        return $this;
    }

}

