<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.VideoDragControl</code>
 */
class VideoDragControl extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VideoDrag VideoDrag = 1;</code>
     */
    protected $VideoDrag = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\VideoDrag $VideoDrag
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VideoDrag VideoDrag = 1;</code>
     * @return \Byteplus\Service\Vod\Models\Business\VideoDrag|null
     */
    public function getVideoDrag()
    {
        return $this->VideoDrag;
    }

    public function hasVideoDrag()
    {
        return isset($this->VideoDrag);
    }

    public function clearVideoDrag()
    {
        unset($this->VideoDrag);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VideoDrag VideoDrag = 1;</code>
     * @param \Byteplus\Service\Vod\Models\Business\VideoDrag $var
     * @return $this
     */
    public function setVideoDrag($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\VideoDrag::class);
        $this->VideoDrag = $var;

        return $this;
    }

}

