<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_upload.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.VodApplyUploadInfoData</code>
 */
class VodApplyUploadInfoData extends \Google\Protobuf\Internal\Message
{
    /**
     * 1001 阶段返回信息 
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodUploadAddress UploadAddress = 1;</code>
     */
    protected $UploadAddress = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\VodUploadAddress $UploadAddress
     *           1001 阶段返回信息 
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodUpload::initOnce();
        parent::__construct($data);
    }

    /**
     * 1001 阶段返回信息 
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodUploadAddress UploadAddress = 1;</code>
     * @return \Byteplus\Service\Vod\Models\Business\VodUploadAddress|null
     */
    public function getUploadAddress()
    {
        return $this->UploadAddress;
    }

    public function hasUploadAddress()
    {
        return isset($this->UploadAddress);
    }

    public function clearUploadAddress()
    {
        unset($this->UploadAddress);
    }

    /**
     * 1001 阶段返回信息 
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodUploadAddress UploadAddress = 1;</code>
     * @param \Byteplus\Service\Vod\Models\Business\VodUploadAddress $var
     * @return $this
     */
    public function setUploadAddress($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\VodUploadAddress::class);
        $this->UploadAddress = $var;

        return $this;
    }

}

