<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.VodCdnStatisticsCommonResult</code>
 */
class VodCdnStatisticsCommonResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.VodCdnStatisticsData Datas = 1;</code>
     */
    private $Datas;
    /**
     * Generated from protobuf field <code>repeated string NoPermissionDomains = 2;</code>
     */
    private $NoPermissionDomains;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\VodCdnStatisticsData[]|\Google\Protobuf\Internal\RepeatedField $Datas
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $NoPermissionDomains
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.VodCdnStatisticsData Datas = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDatas()
    {
        return $this->Datas;
    }

    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.VodCdnStatisticsData Datas = 1;</code>
     * @param \Byteplus\Service\Vod\Models\Business\VodCdnStatisticsData[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDatas($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Byteplus\Service\Vod\Models\Business\VodCdnStatisticsData::class);
        $this->Datas = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string NoPermissionDomains = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNoPermissionDomains()
    {
        return $this->NoPermissionDomains;
    }

    /**
     * Generated from protobuf field <code>repeated string NoPermissionDomains = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNoPermissionDomains($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->NoPermissionDomains = $arr;

        return $this;
    }

}

