<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.VodCompressionRules</code>
 */
class VodCompressionRules extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool IsModify = 1;</code>
     */
    protected $IsModify = false;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.Compression Compression = 2;</code>
     */
    protected $Compression = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $IsModify
     *     @type \Byteplus\Service\Vod\Models\Business\Compression $Compression
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool IsModify = 1;</code>
     * @return bool
     */
    public function getIsModify()
    {
        return $this->IsModify;
    }

    /**
     * Generated from protobuf field <code>bool IsModify = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsModify($var)
    {
        GPBUtil::checkBool($var);
        $this->IsModify = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.Compression Compression = 2;</code>
     * @return \Byteplus\Service\Vod\Models\Business\Compression|null
     */
    public function getCompression()
    {
        return $this->Compression;
    }

    public function hasCompression()
    {
        return isset($this->Compression);
    }

    public function clearCompression()
    {
        unset($this->Compression);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.Compression Compression = 2;</code>
     * @param \Byteplus\Service\Vod\Models\Business\Compression $var
     * @return $this
     */
    public function setCompression($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\Compression::class);
        $this->Compression = $var;

        return $this;
    }

}

