<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.VodDomainCacheConfig</code>
 */
class VodDomainCacheConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodCache VodCache = 1;</code>
     */
    protected $VodCache = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodCacheKey VodCacheKey = 2;</code>
     */
    protected $VodCacheKey = null;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodNegativeCache VodNegativeCache = 3;</code>
     */
    protected $VodNegativeCache = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\VodCache $VodCache
     *     @type \Byteplus\Service\Vod\Models\Business\VodCacheKey $VodCacheKey
     *     @type \Byteplus\Service\Vod\Models\Business\VodNegativeCache $VodNegativeCache
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodCache VodCache = 1;</code>
     * @return \Byteplus\Service\Vod\Models\Business\VodCache|null
     */
    public function getVodCache()
    {
        return $this->VodCache;
    }

    public function hasVodCache()
    {
        return isset($this->VodCache);
    }

    public function clearVodCache()
    {
        unset($this->VodCache);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodCache VodCache = 1;</code>
     * @param \Byteplus\Service\Vod\Models\Business\VodCache $var
     * @return $this
     */
    public function setVodCache($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\VodCache::class);
        $this->VodCache = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodCacheKey VodCacheKey = 2;</code>
     * @return \Byteplus\Service\Vod\Models\Business\VodCacheKey|null
     */
    public function getVodCacheKey()
    {
        return $this->VodCacheKey;
    }

    public function hasVodCacheKey()
    {
        return isset($this->VodCacheKey);
    }

    public function clearVodCacheKey()
    {
        unset($this->VodCacheKey);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodCacheKey VodCacheKey = 2;</code>
     * @param \Byteplus\Service\Vod\Models\Business\VodCacheKey $var
     * @return $this
     */
    public function setVodCacheKey($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\VodCacheKey::class);
        $this->VodCacheKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodNegativeCache VodNegativeCache = 3;</code>
     * @return \Byteplus\Service\Vod\Models\Business\VodNegativeCache|null
     */
    public function getVodNegativeCache()
    {
        return $this->VodNegativeCache;
    }

    public function hasVodNegativeCache()
    {
        return isset($this->VodNegativeCache);
    }

    public function clearVodNegativeCache()
    {
        unset($this->VodNegativeCache);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodNegativeCache VodNegativeCache = 3;</code>
     * @param \Byteplus\Service\Vod\Models\Business\VodNegativeCache $var
     * @return $this
     */
    public function setVodNegativeCache($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\VodNegativeCache::class);
        $this->VodNegativeCache = $var;

        return $this;
    }

}

