<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_common.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.VodGetFairPlayCertInfoResult</code>
 */
class VodGetFairPlayCertInfoResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string CertId = 1;</code>
     */
    protected $CertId = '';
    /**
     * Generated from protobuf field <code>string CertName = 2;</code>
     */
    protected $CertName = '';
    /**
     * Generated from protobuf field <code>string CertFileName = 3;</code>
     */
    protected $CertFileName = '';
    /**
     * Generated from protobuf field <code>string PkFileName = 4;</code>
     */
    protected $PkFileName = '';
    /**
     * Generated from protobuf field <code>string PkPassword = 5;</code>
     */
    protected $PkPassword = '';
    /**
     * Generated from protobuf field <code>string Ask = 6;</code>
     */
    protected $Ask = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $CertId
     *     @type string $CertName
     *     @type string $CertFileName
     *     @type string $PkFileName
     *     @type string $PkPassword
     *     @type string $Ask
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string CertId = 1;</code>
     * @return string
     */
    public function getCertId()
    {
        return $this->CertId;
    }

    /**
     * Generated from protobuf field <code>string CertId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCertId($var)
    {
        GPBUtil::checkString($var, True);
        $this->CertId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string CertName = 2;</code>
     * @return string
     */
    public function getCertName()
    {
        return $this->CertName;
    }

    /**
     * Generated from protobuf field <code>string CertName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCertName($var)
    {
        GPBUtil::checkString($var, True);
        $this->CertName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string CertFileName = 3;</code>
     * @return string
     */
    public function getCertFileName()
    {
        return $this->CertFileName;
    }

    /**
     * Generated from protobuf field <code>string CertFileName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCertFileName($var)
    {
        GPBUtil::checkString($var, True);
        $this->CertFileName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string PkFileName = 4;</code>
     * @return string
     */
    public function getPkFileName()
    {
        return $this->PkFileName;
    }

    /**
     * Generated from protobuf field <code>string PkFileName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPkFileName($var)
    {
        GPBUtil::checkString($var, True);
        $this->PkFileName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string PkPassword = 5;</code>
     * @return string
     */
    public function getPkPassword()
    {
        return $this->PkPassword;
    }

    /**
     * Generated from protobuf field <code>string PkPassword = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPkPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->PkPassword = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Ask = 6;</code>
     * @return string
     */
    public function getAsk()
    {
        return $this->Ask;
    }

    /**
     * Generated from protobuf field <code>string Ask = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAsk($var)
    {
        GPBUtil::checkString($var, True);
        $this->Ask = $var;

        return $this;
    }

}

