<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_media.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.VodGetAudioInfoForAuditResult</code>
 */
class VodGetAudioInfoForAuditResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodAudioInfoForAudit AudioInfo = 1;</code>
     */
    protected $AudioInfo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\VodAudioInfoForAudit $AudioInfo
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodMedia::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodAudioInfoForAudit AudioInfo = 1;</code>
     * @return \Byteplus\Service\Vod\Models\Business\VodAudioInfoForAudit|null
     */
    public function getAudioInfo()
    {
        return $this->AudioInfo;
    }

    public function hasAudioInfo()
    {
        return isset($this->AudioInfo);
    }

    public function clearAudioInfo()
    {
        unset($this->AudioInfo);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodAudioInfoForAudit AudioInfo = 1;</code>
     * @param \Byteplus\Service\Vod\Models\Business\VodAudioInfoForAudit $var
     * @return $this
     */
    public function setAudioInfo($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\VodAudioInfoForAudit::class);
        $this->AudioInfo = $var;

        return $this;
    }

}

