<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.VodListCdnTopAccessUrlResult</code>
 */
class VodListCdnTopAccessUrlResult extends \Google\Protobuf\Internal\Message
{
    /**
     * TopURL查询得到的数据明细以及全部域名的汇总值
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.VodCdnTopAccessUrlElement UrlInfos = 1;</code>
     */
    private $UrlInfos;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\VodCdnTopAccessUrlElement[]|\Google\Protobuf\Internal\RepeatedField $UrlInfos
     *           TopURL查询得到的数据明细以及全部域名的汇总值
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * TopURL查询得到的数据明细以及全部域名的汇总值
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.VodCdnTopAccessUrlElement UrlInfos = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUrlInfos()
    {
        return $this->UrlInfos;
    }

    /**
     * TopURL查询得到的数据明细以及全部域名的汇总值
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.VodCdnTopAccessUrlElement UrlInfos = 1;</code>
     * @param \Byteplus\Service\Vod\Models\Business\VodCdnTopAccessUrlElement[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUrlInfos($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Byteplus\Service\Vod\Models\Business\VodCdnTopAccessUrlElement::class);
        $this->UrlInfos = $arr;

        return $this;
    }

}

