<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.VodListCdnTopAccessResult</code>
 */
class VodListCdnTopAccessResult extends \Google\Protobuf\Internal\Message
{
    /**
     * 热点数据查询得到的数据明细以及全部域名的汇总值
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.VodCdnTopAccessElement ItemInfos = 1;</code>
     */
    private $ItemInfos;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\VodCdnTopAccessElement[]|\Google\Protobuf\Internal\RepeatedField $ItemInfos
     *           热点数据查询得到的数据明细以及全部域名的汇总值
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * 热点数据查询得到的数据明细以及全部域名的汇总值
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.VodCdnTopAccessElement ItemInfos = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItemInfos()
    {
        return $this->ItemInfos;
    }

    /**
     * 热点数据查询得到的数据明细以及全部域名的汇总值
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.VodCdnTopAccessElement ItemInfos = 1;</code>
     * @param \Byteplus\Service\Vod\Models\Business\VodCdnTopAccessElement[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItemInfos($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Byteplus\Service\Vod\Models\Business\VodCdnTopAccessElement::class);
        $this->ItemInfos = $arr;

        return $this;
    }

}

