<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.VodListCdnRegionAndIspResult</code>
 */
class VodListCdnRegionAndIspResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.VodIsp Isps = 1;</code>
     */
    private $Isps;
    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.VodRegion Regions = 2;</code>
     */
    private $Regions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\VodIsp[]|\Google\Protobuf\Internal\RepeatedField $Isps
     *     @type \Byteplus\Service\Vod\Models\Business\VodRegion[]|\Google\Protobuf\Internal\RepeatedField $Regions
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.VodIsp Isps = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIsps()
    {
        return $this->Isps;
    }

    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.VodIsp Isps = 1;</code>
     * @param \Byteplus\Service\Vod\Models\Business\VodIsp[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIsps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Byteplus\Service\Vod\Models\Business\VodIsp::class);
        $this->Isps = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.VodRegion Regions = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRegions()
    {
        return $this->Regions;
    }

    /**
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.VodRegion Regions = 2;</code>
     * @param \Byteplus\Service\Vod\Models\Business\VodRegion[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRegions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Byteplus\Service\Vod\Models\Business\VodRegion::class);
        $this->Regions = $arr;

        return $this;
    }

}

