<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.VodListCdnAccessLogResult</code>
 */
class VodListCdnAccessLogResult extends \Google\Protobuf\Internal\Message
{
    /**
     * 日志列表
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.VodCdnAccessLogInfo Logs = 1;</code>
     */
    private $Logs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Byteplus\Service\Vod\Models\Business\VodCdnAccessLogInfo[]|\Google\Protobuf\Internal\RepeatedField $Logs
     *           日志列表
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * 日志列表
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.VodCdnAccessLogInfo Logs = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLogs()
    {
        return $this->Logs;
    }

    /**
     * 日志列表
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.VodCdnAccessLogInfo Logs = 1;</code>
     * @param \Byteplus\Service\Vod\Models\Business\VodCdnAccessLogInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLogs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Byteplus\Service\Vod\Models\Business\VodCdnAccessLogInfo::class);
        $this->Logs = $arr;

        return $this;
    }

}

