<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_upload.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.VodParseUploadManifestData</code>
 */
class VodParseUploadManifestData extends \Google\Protobuf\Internal\Message
{
    /**
     * 分片列表 
     *
     * Generated from protobuf field <code>repeated string MediaSegments = 1;</code>
     */
    private $MediaSegments;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $MediaSegments
     *           分片列表 
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodUpload::initOnce();
        parent::__construct($data);
    }

    /**
     * 分片列表 
     *
     * Generated from protobuf field <code>repeated string MediaSegments = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMediaSegments()
    {
        return $this->MediaSegments;
    }

    /**
     * 分片列表 
     *
     * Generated from protobuf field <code>repeated string MediaSegments = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMediaSegments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->MediaSegments = $arr;

        return $this;
    }

}

