<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.VodReferersControl</code>
 */
class VodReferersControl extends \Google\Protobuf\Internal\Message
{
    /**
     * referer类型
     *
     * Generated from protobuf field <code>int32 RefererType = 4;</code>
     */
    protected $RefererType = 0;
    /**
     * referer内容
     *
     * Generated from protobuf field <code>repeated string Referers = 5;</code>
     */
    private $Referers;
    /**
     * referer是否可空
     *
     * Generated from protobuf field <code>bool CanEmpty = 6;</code>
     */
    protected $CanEmpty = false;
    /**
     * referer开启状态
     *
     * Generated from protobuf field <code>string Status = 7;</code>
     */
    protected $Status = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $RefererType
     *           referer类型
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Referers
     *           referer内容
     *     @type bool $CanEmpty
     *           referer是否可空
     *     @type string $Status
     *           referer开启状态
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * referer类型
     *
     * Generated from protobuf field <code>int32 RefererType = 4;</code>
     * @return int
     */
    public function getRefererType()
    {
        return $this->RefererType;
    }

    /**
     * referer类型
     *
     * Generated from protobuf field <code>int32 RefererType = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setRefererType($var)
    {
        GPBUtil::checkInt32($var);
        $this->RefererType = $var;

        return $this;
    }

    /**
     * referer内容
     *
     * Generated from protobuf field <code>repeated string Referers = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getReferers()
    {
        return $this->Referers;
    }

    /**
     * referer内容
     *
     * Generated from protobuf field <code>repeated string Referers = 5;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setReferers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Referers = $arr;

        return $this;
    }

    /**
     * referer是否可空
     *
     * Generated from protobuf field <code>bool CanEmpty = 6;</code>
     * @return bool
     */
    public function getCanEmpty()
    {
        return $this->CanEmpty;
    }

    /**
     * referer是否可空
     *
     * Generated from protobuf field <code>bool CanEmpty = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setCanEmpty($var)
    {
        GPBUtil::checkBool($var);
        $this->CanEmpty = $var;

        return $this;
    }

    /**
     * referer开启状态
     *
     * Generated from protobuf field <code>string Status = 7;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     * referer开启状态
     *
     * Generated from protobuf field <code>string Status = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->Status = $var;

        return $this;
    }

}

