<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.VodReferers</code>
 */
class VodReferers extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool IsModify = 1;</code>
     */
    protected $IsModify = false;
    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodReferersControl VodReferersControl = 2;</code>
     */
    protected $VodReferersControl = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $IsModify
     *     @type \Byteplus\Service\Vod\Models\Business\VodReferersControl $VodReferersControl
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool IsModify = 1;</code>
     * @return bool
     */
    public function getIsModify()
    {
        return $this->IsModify;
    }

    /**
     * Generated from protobuf field <code>bool IsModify = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsModify($var)
    {
        GPBUtil::checkBool($var);
        $this->IsModify = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodReferersControl VodReferersControl = 2;</code>
     * @return \Byteplus\Service\Vod\Models\Business\VodReferersControl|null
     */
    public function getVodReferersControl()
    {
        return $this->VodReferersControl;
    }

    public function hasVodReferersControl()
    {
        return isset($this->VodReferersControl);
    }

    public function clearVodReferersControl()
    {
        unset($this->VodReferersControl);
    }

    /**
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodReferersControl VodReferersControl = 2;</code>
     * @param \Byteplus\Service\Vod\Models\Business\VodReferersControl $var
     * @return $this
     */
    public function setVodReferersControl($var)
    {
        GPBUtil::checkMessage($var, \Byteplus\Service\Vod\Models\Business\VodReferersControl::class);
        $this->VodReferersControl = $var;

        return $this;
    }

}

