<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/business/vod_cdn.proto

namespace Byteplus\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Business.VodTopData</code>
 */
class VodTopData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ItemKey = 1;</code>
     */
    protected $ItemKey = '';
    /**
     * Generated from protobuf field <code>string ItemKeyCN = 2;</code>
     */
    protected $ItemKeyCN = '';
    /**
     * Generated from protobuf field <code>double Bandwidth = 3;</code>
     */
    protected $Bandwidth = 0.0;
    /**
     * Generated from protobuf field <code>int64 BandwidthPeakTime = 4;</code>
     */
    protected $BandwidthPeakTime = 0;
    /**
     * Generated from protobuf field <code>double Flux = 5;</code>
     */
    protected $Flux = 0.0;
    /**
     * Generated from protobuf field <code>double FluxRatio = 6;</code>
     */
    protected $FluxRatio = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ItemKey
     *     @type string $ItemKeyCN
     *     @type float $Bandwidth
     *     @type int|string $BandwidthPeakTime
     *     @type float $Flux
     *     @type float $FluxRatio
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ItemKey = 1;</code>
     * @return string
     */
    public function getItemKey()
    {
        return $this->ItemKey;
    }

    /**
     * Generated from protobuf field <code>string ItemKey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setItemKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->ItemKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ItemKeyCN = 2;</code>
     * @return string
     */
    public function getItemKeyCN()
    {
        return $this->ItemKeyCN;
    }

    /**
     * Generated from protobuf field <code>string ItemKeyCN = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setItemKeyCN($var)
    {
        GPBUtil::checkString($var, True);
        $this->ItemKeyCN = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double Bandwidth = 3;</code>
     * @return float
     */
    public function getBandwidth()
    {
        return $this->Bandwidth;
    }

    /**
     * Generated from protobuf field <code>double Bandwidth = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setBandwidth($var)
    {
        GPBUtil::checkDouble($var);
        $this->Bandwidth = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 BandwidthPeakTime = 4;</code>
     * @return int|string
     */
    public function getBandwidthPeakTime()
    {
        return $this->BandwidthPeakTime;
    }

    /**
     * Generated from protobuf field <code>int64 BandwidthPeakTime = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBandwidthPeakTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->BandwidthPeakTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double Flux = 5;</code>
     * @return float
     */
    public function getFlux()
    {
        return $this->Flux;
    }

    /**
     * Generated from protobuf field <code>double Flux = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setFlux($var)
    {
        GPBUtil::checkDouble($var);
        $this->Flux = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double FluxRatio = 6;</code>
     * @return float
     */
    public function getFluxRatio()
    {
        return $this->FluxRatio;
    }

    /**
     * Generated from protobuf field <code>double FluxRatio = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setFluxRatio($var)
    {
        GPBUtil::checkDouble($var);
        $this->FluxRatio = $var;

        return $this;
    }

}

