// Code generated by protoc-gen-byteplus-sdk
// source: describeVodRealtimeMediaData
// DO NOT EDIT!
<?php
require('../../vendor/autoload.php');

$client = Byteplus\Service\Vod\Vod::getInstance();
$client->setAccessKey('your ak');
$client->setSecretKey('your sk');

$request = new Byteplus\Service\Vod\Models\Request\DescribeVodRealtimeMediaDataRequest();
$request->setSpaceList("your SpaceList");
$request->setStartTime("your StartTime");
$request->setEndTime("your EndTime");
$request->setProcessType("your ProcessType");
$request->setAggregation(0);
$request->setDetailFieldList("your DetailFieldList");


$response = new Byteplus\Service\Vod\Models\Response\DescribeVodRealtimeMediaDataResponse();
try {
    $response = $client->describeVodRealtimeMediaData($request);
} catch (Exception $e) {
    echo $e, "\n";
} catch (Throwable $e) {
    echo $e, "\n";
}
if ($response != null && $response->getResponseMetadata() != null && $response->getResponseMetadata()->getError() != null) {
    echo $response->getResponseMetadata()->getError()->serializeToJsonString(), "\n";
} else {
    echo $response->serializeToJsonString(), "\n";
}
