// Code generated by protoc-gen-byteplus-sdk
// source: listSpace
// DO NOT EDIT!
<?php
require('../../vendor/autoload.php');

$client = Byteplus\Service\Vod\Vod::getInstance();
$client->setAccessKey('');
$client->setSecretKey('');

$request = new Byteplus\Service\Vod\Models\Request\VodListSpaceRequest();
$request->setOffset(0);
$request->setLimit(0);


$response = new Byteplus\Service\Vod\Models\Response\VodListSpaceResponse();
try {
    $response = $client->listSpace($request);
} catch (Exception $e) {
    echo $e, "\n";
} catch (Throwable $e) {
    echo $e, "\n";
}
if ($response != null && $response->getResponseMetadata() != null && $response->getResponseMetadata()->getError() != null) {
    echo $response->getResponseMetadata()->getError()->serializeToJsonString(), "\n";
} else {
    echo $response->serializeToJsonString(), "\n";
}
