// Code generated by protoc-gen-byteplus-sdk
// source: listCdnUsageData
// DO NOT EDIT!
<?php
require('../../vendor/autoload.php');

$client = Byteplus\Service\Vod\Vod::getInstance();
$client->setAccessKey('your ak');
$client->setSecretKey('your sk');

$request = new Byteplus\Service\Vod\Models\Request\VodListCdnUsageDataRequest();
$request->setDomains("your Domains");
$request->setInterval("your Interval");
$request->setStartTimestamp(0);
$request->setEndTimestamp(0);
$request->setDataType("your DataType");
$request->setMetric("your Metric");
$request->setNeedDetail(false);


$response = new Byteplus\Service\Vod\Models\Response\VodCdnStatisticsCommonResponse();
try {
    $response = $client->listCdnUsageData($request);
} catch (Exception $e) {
    echo $e, "\n";
} catch (Throwable $e) {
    echo $e, "\n";
}
if ($response != null && $response->getResponseMetadata() != null && $response->getResponseMetadata()->getError() != null) {
    echo $response->getResponseMetadata()->getError()->serializeToJsonString(), "\n";
} else {
    echo $response->serializeToJsonString(), "\n";
}
