// Code generated by protoc-gen-byteplus-sdk
// source: describeVodDomainBandwidthData
// DO NOT EDIT!
<?php
require('../../vendor/autoload.php');

$client = Byteplus\Service\Vod\Vod::getInstance();
$client->setAccessKey('your ak');
$client->setSecretKey('your sk');

$request = new Byteplus\Service\Vod\Models\Request\VodDescribeVodDomainBandwidthDataRequest();
$request->setDomainList("your DomainList");
$request->setStartTime("your StartTime");
$request->setEndTime("your EndTime");
$request->setAggregation(0);
$request->setBandwidthType("your BandwidthType");
$request->setArea("your Area");


$response = new Byteplus\Service\Vod\Models\Response\VodDescribeVodDomainBandwidthDataResponse();
try {
    $response = $client->describeVodDomainBandwidthData($request);
} catch (Exception $e) {
    echo $e, "\n";
} catch (Throwable $e) {
    echo $e, "\n";
}
if ($response != null && $response->getResponseMetadata() != null && $response->getResponseMetadata()->getError() != null) {
    echo $response->getResponseMetadata()->getError()->serializeToJsonString(), "\n";
} else {
    echo $response->serializeToJsonString(), "\n";
}
