// Code generated by protoc-gen-byteplus-sdk
// source: getPlaylists
// DO NOT EDIT!
<?php
require('../../vendor/autoload.php');

$client = Byteplus\Service\Vod\Vod::getInstance();
$client->setAccessKey('your ak');
$client->setSecretKey('your sk');

$request = new Byteplus\Service\Vod\Models\Request\VodGetPlaylistsRequest();
$request->setSpaceName("your SpaceName");
$request->setIds("your Ids");
$request->setName("your Name");
$request->setLimit(0);
$request->setOffset(0);


$response = new Byteplus\Service\Vod\Models\Response\VodGetPlaylistsResponse();
try {
    $response = $client->getPlaylists($request);
} catch (Exception $e) {
    echo $e, "\n";
} catch (Throwable $e) {
    echo $e, "\n";
}
if ($response != null && $response->getResponseMetadata() != null && $response->getResponseMetadata()->getError() != null) {
    echo $response->getResponseMetadata()->getError()->serializeToJsonString(), "\n";
} else {
    echo $response->serializeToJsonString(), "\n";
}
