// Code generated by protoc-gen-byteplus-sdk
// source: listCdnTopAccess
// DO NOT EDIT!
<?php
require('../../vendor/autoload.php');

$client = Byteplus\Service\Vod\Vod::getInstance();
$client->setAccessKey('your ak');
$client->setSecretKey('your sk');

$request = new Byteplus\Service\Vod\Models\Request\VodListCdnTopAccessRequest();
$request->setDomains("your Domains");
$request->setStartTimestamp(0);
$request->setEndTimestamp(0);
$request->setSortType("your SortType");
$request->setItem("your Item");


$response = new Byteplus\Service\Vod\Models\Response\VodListCdnTopAccessResponse();
try {
    $response = $client->listCdnTopAccess($request);
} catch (Exception $e) {
    echo $e, "\n";
} catch (Throwable $e) {
    echo $e, "\n";
}
if ($response != null && $response->getResponseMetadata() != null && $response->getResponseMetadata()->getError() != null) {
    echo $response->getResponseMetadata()->getError()->serializeToJsonString(), "\n";
} else {
    echo $response->serializeToJsonString(), "\n";
}
