// Code generated by protoc-gen-byteplus-sdk
// source: createPlaylist
// DO NOT EDIT!
<?php
require('../../vendor/autoload.php');

$client = Byteplus\Service\Vod\Vod::getInstance();
$client->setAccessKey('your ak');
$client->setSecretKey('your sk');

$request = new Byteplus\Service\Vod\Models\Request\VodCreatePlaylistRequest();
$request->setSpaceName("your SpaceName");
$request->setName("your Name");
$request->setFormat("your Format");
$request->setCodec("your Codec");
$request->setDefinition("your Definition");
$request->setVids("your Vids");
$request->setStartTime("your StartTime");
$request->setEndTime("your EndTime");
$request->setCycles("your Cycles");


$response = new Byteplus\Service\Vod\Models\Response\VodCreatePlaylistResponse();
try {
    $response = $client->createPlaylist($request);
} catch (Exception $e) {
    echo $e, "\n";
} catch (Throwable $e) {
    echo $e, "\n";
}
if ($response != null && $response->getResponseMetadata() != null && $response->getResponseMetadata()->getError() != null) {
    echo $response->getResponseMetadata()->getError()->serializeToJsonString(), "\n";
} else {
    echo $response->serializeToJsonString(), "\n";
}
