<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/request/request_vod.proto

namespace Byteplus\Service\Vod\Models\Request;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Request.UpdateDomainOriginInfoV2Request</code>
 */
class UpdateDomainOriginInfoV2Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string SpaceName = 1;</code>
     */
    protected $SpaceName = '';
    /**
     * Generated from protobuf field <code>string DomainType = 2;</code>
     */
    protected $DomainType = '';
    /**
     * Generated from protobuf field <code>string Domain = 3;</code>
     */
    protected $Domain = '';
    /**
     *源站地址类型
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodDomainSourceStationAddressType SourceStationAddressType = 4;</code>
     */
    protected $SourceStationAddressType = 0;
    /**
     * 源站列表
     *
     * Generated from protobuf field <code>repeated string Origins = 5;</code>
     */
    private $Origins;
    /**
     * 加速区域
     *
     * Generated from protobuf field <code>string Area = 6;</code>
     */
    protected $Area = '';
    /**
     * 源站配置模块
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.CdnOriginRule Origin = 7;</code>
     */
    private $Origin;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $SpaceName
     *     @type string $DomainType
     *     @type string $Domain
     *     @type int $SourceStationAddressType
     *          源站地址类型
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Origins
     *           源站列表
     *     @type string $Area
     *           加速区域
     *     @type \Byteplus\Service\Vod\Models\Business\CdnOriginRule[]|\Google\Protobuf\Internal\RepeatedField $Origin
     *           源站配置模块
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\RequestVod::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string SpaceName = 1;</code>
     * @return string
     */
    public function getSpaceName()
    {
        return $this->SpaceName;
    }

    /**
     * Generated from protobuf field <code>string SpaceName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSpaceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->SpaceName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string DomainType = 2;</code>
     * @return string
     */
    public function getDomainType()
    {
        return $this->DomainType;
    }

    /**
     * Generated from protobuf field <code>string DomainType = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDomainType($var)
    {
        GPBUtil::checkString($var, True);
        $this->DomainType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Domain = 3;</code>
     * @return string
     */
    public function getDomain()
    {
        return $this->Domain;
    }

    /**
     * Generated from protobuf field <code>string Domain = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDomain($var)
    {
        GPBUtil::checkString($var, True);
        $this->Domain = $var;

        return $this;
    }

    /**
     *源站地址类型
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodDomainSourceStationAddressType SourceStationAddressType = 4;</code>
     * @return int
     */
    public function getSourceStationAddressType()
    {
        return $this->SourceStationAddressType;
    }

    /**
     *源站地址类型
     *
     * Generated from protobuf field <code>.Byteplus.Vod.Models.Business.VodDomainSourceStationAddressType SourceStationAddressType = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSourceStationAddressType($var)
    {
        GPBUtil::checkEnum($var, \Byteplus\Service\Vod\Models\Business\VodDomainSourceStationAddressType::class);
        $this->SourceStationAddressType = $var;

        return $this;
    }

    /**
     * 源站列表
     *
     * Generated from protobuf field <code>repeated string Origins = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrigins()
    {
        return $this->Origins;
    }

    /**
     * 源站列表
     *
     * Generated from protobuf field <code>repeated string Origins = 5;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrigins($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Origins = $arr;

        return $this;
    }

    /**
     * 加速区域
     *
     * Generated from protobuf field <code>string Area = 6;</code>
     * @return string
     */
    public function getArea()
    {
        return $this->Area;
    }

    /**
     * 加速区域
     *
     * Generated from protobuf field <code>string Area = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setArea($var)
    {
        GPBUtil::checkString($var, True);
        $this->Area = $var;

        return $this;
    }

    /**
     * 源站配置模块
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.CdnOriginRule Origin = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrigin()
    {
        return $this->Origin;
    }

    /**
     * 源站配置模块
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.CdnOriginRule Origin = 7;</code>
     * @param \Byteplus\Service\Vod\Models\Business\CdnOriginRule[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrigin($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Byteplus\Service\Vod\Models\Business\CdnOriginRule::class);
        $this->Origin = $arr;

        return $this;
    }

}

