<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/request/request_vod.proto

namespace Byteplus\Service\Vod\Models\Request;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Request.VodCreateDomainV2Request</code>
 */
class VodCreateDomainV2Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string SpaceName = 1;</code>
     */
    protected $SpaceName = '';
    /**
     * Generated from protobuf field <code>string DomainType = 2;</code>
     */
    protected $DomainType = '';
    /**
     * 域名
     *
     * Generated from protobuf field <code>string Domain = 3;</code>
     */
    protected $Domain = '';
    /**
     * Generated from protobuf field <code>int32 SourceStationType = 5;</code>
     */
    protected $SourceStationType = 0;
    /**
     *源站地址类型
     *
     * Generated from protobuf field <code>int32 SourceStationAddressType = 6;</code>
     */
    protected $SourceStationAddressType = 0;
    /**
     *  string Origins = 7;                  //源站地址，这个参数在历史 SDK
     *  不可用，所以废弃，后续可以使用编号 11 的 Origin 参数
     *
     * Generated from protobuf field <code>string Area = 8;</code>
     */
    protected $Area = '';
    /**
     *挂载tos 桶名称
     *
     * Generated from protobuf field <code>string BucketName = 9;</code>
     */
    protected $BucketName = '';
    /**
     * 源站列表
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.CdnOriginRule Origin = 11;</code>
     */
    private $Origin;
    /**
     * 回源Host
     *
     * Generated from protobuf field <code>string Host = 16;</code>
     */
    protected $Host = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $SpaceName
     *     @type string $DomainType
     *     @type string $Domain
     *           域名
     *     @type int $SourceStationType
     *     @type int $SourceStationAddressType
     *          源站地址类型
     *     @type string $Area
     *            string Origins = 7;                  //源站地址，这个参数在历史 SDK
     *            不可用，所以废弃，后续可以使用编号 11 的 Origin 参数
     *     @type string $BucketName
     *          挂载tos 桶名称
     *     @type \Byteplus\Service\Vod\Models\Business\CdnOriginRule[]|\Google\Protobuf\Internal\RepeatedField $Origin
     *           源站列表
     *     @type string $Host
     *           回源Host
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\RequestVod::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string SpaceName = 1;</code>
     * @return string
     */
    public function getSpaceName()
    {
        return $this->SpaceName;
    }

    /**
     * Generated from protobuf field <code>string SpaceName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSpaceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->SpaceName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string DomainType = 2;</code>
     * @return string
     */
    public function getDomainType()
    {
        return $this->DomainType;
    }

    /**
     * Generated from protobuf field <code>string DomainType = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDomainType($var)
    {
        GPBUtil::checkString($var, True);
        $this->DomainType = $var;

        return $this;
    }

    /**
     * 域名
     *
     * Generated from protobuf field <code>string Domain = 3;</code>
     * @return string
     */
    public function getDomain()
    {
        return $this->Domain;
    }

    /**
     * 域名
     *
     * Generated from protobuf field <code>string Domain = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDomain($var)
    {
        GPBUtil::checkString($var, True);
        $this->Domain = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 SourceStationType = 5;</code>
     * @return int
     */
    public function getSourceStationType()
    {
        return $this->SourceStationType;
    }

    /**
     * Generated from protobuf field <code>int32 SourceStationType = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setSourceStationType($var)
    {
        GPBUtil::checkInt32($var);
        $this->SourceStationType = $var;

        return $this;
    }

    /**
     *源站地址类型
     *
     * Generated from protobuf field <code>int32 SourceStationAddressType = 6;</code>
     * @return int
     */
    public function getSourceStationAddressType()
    {
        return $this->SourceStationAddressType;
    }

    /**
     *源站地址类型
     *
     * Generated from protobuf field <code>int32 SourceStationAddressType = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setSourceStationAddressType($var)
    {
        GPBUtil::checkInt32($var);
        $this->SourceStationAddressType = $var;

        return $this;
    }

    /**
     *  string Origins = 7;                  //源站地址，这个参数在历史 SDK
     *  不可用，所以废弃，后续可以使用编号 11 的 Origin 参数
     *
     * Generated from protobuf field <code>string Area = 8;</code>
     * @return string
     */
    public function getArea()
    {
        return $this->Area;
    }

    /**
     *  string Origins = 7;                  //源站地址，这个参数在历史 SDK
     *  不可用，所以废弃，后续可以使用编号 11 的 Origin 参数
     *
     * Generated from protobuf field <code>string Area = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setArea($var)
    {
        GPBUtil::checkString($var, True);
        $this->Area = $var;

        return $this;
    }

    /**
     *挂载tos 桶名称
     *
     * Generated from protobuf field <code>string BucketName = 9;</code>
     * @return string
     */
    public function getBucketName()
    {
        return $this->BucketName;
    }

    /**
     *挂载tos 桶名称
     *
     * Generated from protobuf field <code>string BucketName = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setBucketName($var)
    {
        GPBUtil::checkString($var, True);
        $this->BucketName = $var;

        return $this;
    }

    /**
     * 源站列表
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.CdnOriginRule Origin = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrigin()
    {
        return $this->Origin;
    }

    /**
     * 源站列表
     *
     * Generated from protobuf field <code>repeated .Byteplus.Vod.Models.Business.CdnOriginRule Origin = 11;</code>
     * @param \Byteplus\Service\Vod\Models\Business\CdnOriginRule[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrigin($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Byteplus\Service\Vod\Models\Business\CdnOriginRule::class);
        $this->Origin = $arr;

        return $this;
    }

    /**
     * 回源Host
     *
     * Generated from protobuf field <code>string Host = 16;</code>
     * @return string
     */
    public function getHost()
    {
        return $this->Host;
    }

    /**
     * 回源Host
     *
     * Generated from protobuf field <code>string Host = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->Host = $var;

        return $this;
    }

}

