<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byteplus/vod/request/request_vod.proto

namespace Byteplus\Service\Vod\Models\Request;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Byteplus.Vod.Models.Request.VodGetPlaylistsRequest</code>
 */
class VodGetPlaylistsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string SpaceName = 1;</code>
     */
    protected $SpaceName = '';
    /**
     * 以,分隔
     *
     * Generated from protobuf field <code>string Ids = 2;</code>
     */
    protected $Ids = '';
    /**
     * Generated from protobuf field <code>string Name = 3;</code>
     */
    protected $Name = '';
    /**
     * Generated from protobuf field <code>uint32 Limit = 4;</code>
     */
    protected $Limit = 0;
    /**
     * Generated from protobuf field <code>uint32 Offset = 5;</code>
     */
    protected $Offset = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $SpaceName
     *     @type string $Ids
     *           以,分隔
     *     @type string $Name
     *     @type int $Limit
     *     @type int $Offset
     * }
     */
    public function __construct($data = NULL) {
        \Byteplus\Service\Vod\Models\GPBMetadata\RequestVod::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string SpaceName = 1;</code>
     * @return string
     */
    public function getSpaceName()
    {
        return $this->SpaceName;
    }

    /**
     * Generated from protobuf field <code>string SpaceName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSpaceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->SpaceName = $var;

        return $this;
    }

    /**
     * 以,分隔
     *
     * Generated from protobuf field <code>string Ids = 2;</code>
     * @return string
     */
    public function getIds()
    {
        return $this->Ids;
    }

    /**
     * 以,分隔
     *
     * Generated from protobuf field <code>string Ids = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->Ids = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * Generated from protobuf field <code>string Name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 Limit = 4;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->Limit;
    }

    /**
     * Generated from protobuf field <code>uint32 Limit = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkUint32($var);
        $this->Limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 Offset = 5;</code>
     * @return int
     */
    public function getOffset()
    {
        return $this->Offset;
    }

    /**
     * Generated from protobuf field <code>uint32 Offset = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkUint32($var);
        $this->Offset = $var;

        return $this;
    }

}

